### ISSUE TITLE
Payload and Rocket Performance information

### ISSUE THREAD

**Issue by TheGLine** [friznit/Unofficial-BDB-Wiki#10]
Potential sources of information for more "theoretical" calculations of payload-to-orbit calculations:

https://spacecraft.ssl.umd.edu/academics/791S16/791S16L03.rocket_perf.pdf
http://silverbirdastronautics.com/LaunchMethodology.pdf

**Comment by friznit** [comment]
Mostly completed LKO payloads, need to test a few.
Add GEO/GTO stats for those rockets which are specialised for it (e.g most of the Centaur variants)

LKO requirements (JNSQ) = >5000 dV with a reasonable TWR using KER as a guide.  Something around >1.2 TWR for first 4k dV or so, then >0.6 for final 1k dV circulisation burn.

**Comment by friznit** [comment]
![Payload_Chart](https://user-images.githubusercontent.com/12999059/76869303-077cf400-6860-11ea-9008-f54329addb5d.png)
