### ISSUE TITLE
Update Atlas Pages

### ISSUE THREAD

**Issue by TheGLine** [friznit/Unofficial-BDB-Wiki#11]
There are some instances where the actual interaction of the upper stage and the lower stage of rockets is not clear.  As an example, when constructing the Atlas-Able, it's not clear to the reader (and it wasn't clear to me until I started reading the information about the parts) that you need Fenris adapters and decouplers to actually connect the Atlas and Able.

I will try to compile a more detailed list of these missing parts; I think the place to update them will be on the upper stage information.

**Comment by friznit** [comment]
Atlas was already fairly well documented in the 'official' BDB wiki and much of this is just copied over to here.  It really needs bringing up to scratch with the other guides now, including a proper build guide.  I've got time this weekend to do it.

#9 Also, the Atlas tapered fuel tank is configurable so you technically don't need the adapter
