### ISSUE TITLE
Transtage RCS

### ISSUE THREAD

**Issue by zorg2044** [friznit/Unofficial-BDB-Wiki#12]
wasn't sure exactly where you would want this placed quoting Cobalt from the forum thread:

"The later Transtage (23C and 34D) switched to a 6 pod design. 4x linear RCS, 2x 2-way RCS. Early (3A, 3C) launches used 2x linear and 2x 3-way.

The 4 way RCS is meant to be used with X-20 or other similar payloads.﻿"

Transtage RCS:
Linear
Radial
2 way
3 way
4 way

https://forum.kerbalspaceprogram.com/index.php?/topic/122020-16x-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v152-%D0%B1%D1%80%D1%83%D0%BD%D0%BE-8feb2019/page/525/&tab=comments#comment-3633386

**Comment by friznit** [comment]
I already summarised that post here: https://github.com/friznit/Unofficial-BDB-Wiki/wiki/Upper-Stages#Transtage

**Comment by CobaltWolf** [comment]
also the Saturn 1B "Big G" is actually a Saturn 1..?
