### ISSUE TITLE
More Probes & Sats

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#18]
A payload for every rocket project...

**BDB**
- [x] Clementine (Titan II(23)G Star-37FM)
- [x] SOLRAD/GRAB/POPPY Blk 2 (Thor Agena-D) [SIGNIT]
- [x] Transit 2A + Solrad 1 (Thor Able-Star) [NAV]
- [x] Transit 3B + LOFTI (Thor Able-Star)
- [x] Transit 4A + Injun 1 + Solrad 3/Grab 2 (Thor Able-Star)
- [x] Transit 5A (Scout-X3)
- [x] Transit 5BN + Transit 5E (Thor Able-Star)
- [x] Transit-O SOOS (Scout-G1)
- [x] Pioneer 10/11
- [x] Pioneer Orbiter (Outer Planets Orbiter Proposal)
- [x] Pioneer SUAE (Saturn/Uranus Atmosphere Entry Proposal)
- [x] RAE
- [x] Beacon Explorer
- [x] Bacon 1
- [x] Mariner 3-5
- [x] Voyager Mars

**ScanSat Parts**
- [x] IKONOS-1 (Athena 2)
- [ ] Worldview-1 (Delta-7920)
- [x] Worldview-3 (Atlas V-401)
- [x] KH-11 (Titan 3D; 34D; IV; Delta IVH)
- [x] EOS-AM 1 (Terra) (Atlas IIAS)
- [x] GOES-R (Atlas V-541)
- [x] Sentinel 2A/2B (Vega)
- [ ] SEASAT (Atlas F Agena-D)
- [x] [Jason-3](https://space.skyrocket.de/doc_sdat/jason-1.htm)
- [x] TerraSAR-X (Dnepr)
- [x] RADARSAT-1 (Delta-7920)
- [ ] RADARSAT-2 (Soyuz-FG Fregat)
- [x] TANDEM-L
- [x] Mars Recon Orbiter (Atlas V-401)
- [x] Europa Clipper
- [x] EO-1 (Delta-7320)

**NF Exploration**

- [ ] [Galileo Antennae](https://spacenews.com/wp-content/uploads/2014/11/Galileo_ESA02-650x485.jpg) - small and large phased arrays
- [x] [EchoStar ](http://www.coloradospacenews.com/wp-content/uploads/2014/09/Satellite_Operations_Header.jpg) - large and medium deployable dishes
- [ ] [5m dish](https://img4.s3wfg.com/web/img/images_uploaded/b/3/inmarsat4_opt.jpg) - with pointy phased array
- [ ] [Iridium OG](https://live.staticflickr.com/3372/3347077242_bb3f600ec6_b.jpg) - deployable phased array panel
- [ ] [Iridium NEXT](https://dyqg1y54vebpp.cloudfront.net/wp-content/uploads/2016/09/img-row-1@2x.png?x58728) - large phased array panel
- [ ] [Small/large dish thing](https://i7.pngguru.com/preview/306/407/699/geosynchronous-satellite-launch-vehicle-south-asia-satellite-indian-space-research-organisation-gsat-polar-satellite-launch-vehicle-narendra-modi.jpg) - same as EchoStar
- [ ] [static dish](https://france3-regions.francetvinfo.fr/occitanie/sites/regions_france3/files/styles/top_big/public/assets/images/2013/12/14/000_par7741643.jpg?itok=dtXdcCqH) - static solid dishes (1-2 sizes)
- [x] [TDRS Gen 1](https://www.nasa.gov/sites/default/files/tdrs_1st_generation.jpg) (STS)
- [x] [TDRS Gen 3](http://spaceflight101.com/atlas-v-tdrs-m/wp-content/uploads/sites/170/2017/08/tdrs-deploy.jpg)
- [ ] [HST High Gain Antenna](https://live.staticflickr.com/8681/27712254083_6c06643175_b.jpg)
- [ ] [EDRS Laser](https://upload.wikimedia.org/wikipedia/commons/8/87/European_Data_Relay_System_laser_communication_terminal.jpg)
- [ ] [Fixed mesh reflectors](https://www.harris.com/sites/default/files/images/solution/Lightweight_Fixed_mesh_Reflector_tcm43-26975_2000x2000.jpg)
- [ ] [ribbed mesh](https://www.harris.com/sites/default/files/images/solution/d0807_Unfurlable%20Space%20Antenna%20Solutions_55430_2000x2000_2.jpg)
- [ ] [Kiku8](https://space.skyrocket.de/img_sat/ets-8__1.jpg)

**Space Dust**

- [x] Hubble ([Scope from Space Dust mod](https://forum.kerbalspaceprogram.com/index.php?/topic/197723-111x-space-dust-atmospheric-and-exospheric-harvesting-march-28/))

**Kitbash**

- [x] Cobe (Delta 5920)
- [x] [Dawn (Discovery 9)](https://space.skyrocket.de/doc_sdat/dawn.htm) (Delta II)
- [x] DSCS-3 (Titan 34D IUS, Delta IV M)
- [x] EchoStar 7 (Atlas IIIB DEC)
- [ ] Eutelsat WS (Delta IV M+)
- [x] Galaxy 1 (Delta 3920)
- [x] Galaxy 10 (Delta III)
- [x] GPS-2 (Delta 6925)
- [x] Insat 1D (Delta 4925)
- [ ] Quasar 1 SDS-1 (Titan III(34)B)
- [x] Quasar 11 SDS-2 (Titan IVA IUS)
- [ ] LADEE (Minotaur V)
- [x] MBSat 1 (Atlas IIIA)
- [ ] MIDAS 1 (Atlas LV3A Agena A)
- [ ] Peregrine 1 (Vulcan Centaur VC25)
- [ ] Starshine 3 (Athena I)
- [x] STPSat 2 (Minotaur IV

**Comment by friznit** [comment]
![Draft2](https://user-images.githubusercontent.com/12999059/62796402-13862380-bad1-11e9-8981-22b2c82e9b35.png)

**Comment by friznit** [comment]
![Atlas LV3 Agena D Mariner 3](https://user-images.githubusercontent.com/12999059/62796422-20a31280-bad1-11e9-9129-9ba67565c74f.png)
Atlas-LV3 Agena-D Mariner 4 (1964)

![Titan IIIE Centaur D1-T Voyager 1](https://user-images.githubusercontent.com/12999059/62796563-7aa3d800-bad1-11e9-8cbf-77bbf6816e22.png)
Titan IIIE Voyager 2 (1977)

![Titan IVB Centaur T Cassini Huygens](https://user-images.githubusercontent.com/12999059/62796612-8ee7d500-bad1-11e9-8f25-c2c02bd3ffbd.png)
Titan IVB Cassini-Huygens (1997)

![Delta II 7925 Mars Odyssey](https://user-images.githubusercontent.com/12999059/62796481-49c3a300-bad1-11e9-93bc-f0396766c23d.png)
Delta II 7925 Mars Odyssey (2001)

![Atlas V 401 Maven](https://user-images.githubusercontent.com/12999059/62796504-5ba54600-bad1-11e9-9208-35846f6f66f4.png)
Atlas V (401) MAVEN (2013)

**Comment by CobaltWolf** [comment]
Whoa

**Comment by friznit** [comment]
Funny multiple satellite thingy wotsit

**Comment by friznit** [comment]
![image](https://user-images.githubusercontent.com/12999059/69477270-0ec55100-0ddc-11ea-8650-bf3a2b06137e.png)

**Comment by Gordon-Dry** [comment]
Aha. Thank you.

**Comment by friznit** [comment]
![BDB Sats](https://user-images.githubusercontent.com/12999059/69832085-53aa1700-1224-11ea-8ae5-b5e3b02b7243.png)

**Comment by friznit** [comment]
![front_Ranger Block 2 Test_4](https://user-images.githubusercontent.com/12999059/69987053-8ca0ff00-1536-11ea-85a3-fccc0836e00f.png)

**Comment by svcino** [comment]
the explorer 7 probe is easy to build

**Comment by CobaltWolf** [comment]
Until I redo it, at least...

**Comment by friznit** [comment]
P10: check IR radiometer depth mask; add telemetry ae to atmo probe

**Comment by friznit** [comment]
![Voyager Mars](https://user-images.githubusercontent.com/12999059/198986735-338e9e68-a31b-4a82-9265-6d4cfc61daea.png)
