### ISSUE TITLE
Suggestion - DCSS for Delta IV

### ISSUE THREAD

**Issue by Drakenexh** [friznit/Unofficial-BDB-Wiki#2]
reDirect SLS ICPS makes a perfect Delta DCSS, in RL is the same part!
![front_Exoliner II - Delta IV_1](https://user-images.githubusercontent.com/26016244/59155211-a74c5c80-8a5a-11e9-846d-2885633cd967.png)

**Comment by friznit** [comment]
Well close enough in real life to be the same.  The SLS ICPS has a few modifications.  You'll note I've included a reference to the reDirect ICPS as an analogue for Delta DCSS on the Upper Stages page.  reDirect only has a 5m version but I've made a tweakscale MM patch to downsize it to 4m for use on Delta III and Delta IV Medium.

If you're suggesting Cobaltwolf makes one...well that'd be a request for the BDB github, not here ;)

**Comment by friznit** [comment]
Update Delta IV with BDB DCSS
Update Upper Stages with same

**Comment by friznit** [comment]
Need DCSS 5m for Delta IV M+ & H.  Tweakscale?

**Comment by zorg2044** [comment]
The new BDB one can be tweakscaled but the proportions will be off. Benjees ICPS should still be the preferred option for accuracy.
