### ISSUE TITLE
Typo in the image in the Vulcan page

### ISSUE THREAD

**Issue by KerbalKore** [friznit/Unofficial-BDB-Wiki#22]
In the image it says “Inon engine moutning plate”

(Sorry if it feels like I’m actively searching for typos to call you out on I’m not I’m just finding them and pointing them out and I just realized the disclaimer is longer than the post bye)

**Comment by friznit** [comment]
It's good - please keep pointing them out!  I'm delighted someone is actually reading the wiki :)

**Comment by KerbalKore** [comment]
Are you kidding? This wiki is awesome!
