### ISSUE TITLE
Thor / Delta & Vanguard Update

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#23]
# Thor
Derived from the PGM-17 Thor intermediate-range ballistic missile, the Thor (BDB Fenris) rocket was the first in a family of space launch vehicles that evolved through four major iterations. Thor-Delta (BDB Daleth) was so-named because it was the fourth Thor-based space launch vehicle after Thor Able, Thor Able-Star, and Thor Agena and eventually the whole rocket came to be known as just Delta. The last derivative of Thor was finally retired in 2018.

There are a huge number of variants as the rocket is continuously upgraded over time with stretched fuel tanks, new engines, upper stages and solid rocket boosters.  Most parts have Variant Part Switches in the Part Action Window and the correct variant to select is indicated in parentheses  in the build guides.

**Fuel Tanks**
- Short Adapter Tank = Fenris-360 1.5m to 1.25m Short Adapter Tank
- Long Adapter Tank = Fenris-600 1.5m to 1.25m Long Adapter Tank
- Short Ext Tank = Fenris-X400 Short Extension Tank
- Long Ext Tank = Fenris-X800 Long Extension Tank
- Upper Tank = Fenris-1400/1560 Upper Tank (B9 Switchable for LT/ELT or EELT)
- Lower Tank = Fenris-1400/2040/2600 Lower Tank (B9 Switchable for Basic/LT, ELT, EELT & Delta III; also Ribbed or Smooth style)

**Structural Adapters/Interstages**
- Short Structural Adapter = Fenris-SFA 1.5m to 1.25m Structural Adapter
- Medium Structural Adapter = Fenris-MCA 1.25m to 0.9375m Structural Adapter (B9 Switchable "Raceways")
- Long Able Adapter = Fenris-LCE 1.25m to 0.9375m Structural Adapter
- Able/Delta Interstage = Fenris-SIF 0.9375m Adapter Interstage (B9 Switchable)
- Thor Interstage = Fenris-SSI 0.9375m Interstage
- Agena-A Interstage = Belle-A 1.25m to 0.9375m Interstage
- Agena Interstage = Belle 0.9375 Interstage
- Delta-K Short/Long Interstage = Daleth-K Interstage (B9 Switchable)
- Delta-III Interstage = Daleth-III-DHSS 2.5m Interstage (B9 Switchable)

### Thor
The fuel volume of the Fenris-Alpha fuel tank should be set to "Able" or "Delta" respectively.  The optional "Stock" setting matches standard stock fuel levels for this size of tank but may imbalance rocket performance.

![image](https://user-images.githubusercontent.com/12999059/75635001-893b1380-5c0a-11ea-8f12-36dd9ba292e4.png)

Tags: Fenris

Variants | First Stage | Boosters | Second Stage | Third Stage |
-- | -- | -- | -- | --
Thor Able       | LR79-NA11 (with 4x fins) | | Fenris-LCE Structural Adapter + Fenris-SIF Interstage (Able Config); Alpha Upper Stage |  |
Thor Able-Star | LR79-NA11 | | Fenris-MCA Structural Adapter + Fenris-SSI Interstage; Alphastar Upper Stage |  |
Thor Burner 2 | LR79-NA11 | | Staara 37B + 3-Axis Control | Staara 26B (Burner 2A) |
Thor Agena-A |LR79-NA11 | | Belle-A Interstage; Belle-A Upper Stage | |
Thor Agena-B/D |LR79-NA11 | | Fenris-MCA Structural Adapter + Belle Interstage; Belle-B/D Upper Stage| |
Thor-Agena B/D (TAT) | LR79-NA13 | 3x Dioscuri 1 | Fenris-MCA Structural Adapter + Belle Interstage; Belle-B/D Upper Stage | |

- Alpha Upper Stage = Fenris/Alpha AGU; Fenris/Alpha-60 Fuel Tank; JA10 "Alpha" Engine (Easton-12-37 Config)
- Alpha-Star Upper Stage = Fenris/Alphastar-160 Fuel Tank; JA10 "Alphastar" Engine (Fenris-18-104 Config)

![Thor Able Build Guide](https://user-images.githubusercontent.com/12999059/95677157-87cbc380-0bbb-11eb-8d88-2dcf891af5ac.png)

_Thor-Able_ rocket.  _Thor-Delta_ (which came to be known as simply Delta) is a similar build except the upper stage uses the longer Fenris Alpha II 120 Liquid Fuel Tank and Fenris Alpha Interstage with the part switch set to 'Delta'.

# Delta
Originally called Thor-Delta because the upper stage was the fourth iteration after Able, Able-Star and Agena, the rocket soon became known simply as Delta to distinguish it from the USAF programme that continued to develop Thor.

Variants | First Stage | Boosters | Second Stage | Third Stage |
-- | -- | -- | -- | --
Delta      | LR79-NA11 with fins | |  Fenris-LCE Structural Adapter + Fenris-SIF Interstage (Delta Config); Alpha Upper Stage | Staara-20-IIA SRM (Optional) |
Delta A  | LR79-NA11 | | Fenris-MCA Structural Adapter + Fenris-SIF Interstage (Delta Config); Alpha Upper Stage | Staara-20-IIA SRM (Optional) |
Delta B/C/C1 | LR79-NA11 | | Same as Delta A but with Daleth B Upper Stage | Staara-20-IIA SRM (Optional) |
Delta D (TAD) | LR79-NA13 | 3x Dioscuri 1 | Same as Delta B | Staara-20-IIA SRM (Optional) |
Delta E (TAID) | LR79-NA13 | 3x Dioscuri 1 | Fenris-MCA Structural Adapter + Fenris-SSI Interstage; Daleth E Upper Stage | Staara-20-IIA SRM |
Delta G (TAID) | LR79-NA13 | 3x Dioscuri 1 | No upper stage | |
Delta J (TAID) | LR79-NA13 | 3x Dioscuri 1 | Same as Delta E | Staara-37DV |

- Daleth B Upper Stage =  Fenris/Alpha AGU; Daleth-B-85 Fuel Tank; JA10 "Alpha" Engine (Daleth-12-118D Config)
- Daleth E Upper Stage = Daleth-E-210 Fuel Tank; JA10 "Alphastar" Engine (Fenris-18-118E Config)

![Delta B E Adapters](https://user-images.githubusercontent.com/12999059/70659602-54956c80-1c58-11ea-8bc7-6bdb5079c871.png)

### Long Tank Thor
While the USAF continued development on Thor Advanced (Thorad), NASA benefited by using the new technology in their parallel Delta programme.  Delta L, M & N all use the Delta E upper stage and either Star-20, Star-37B or no SRM respectively.  The thrust augmented Delta M6 and N6 dubbed "Super Six" adds six Castor 2 SRBs.  Although the naming convention changed from lettering to a numerical designation, the 100-series are essentially the same rocket with an upgraded Delta F upper stage.  Concept studies also looked at using a cryogenic Hydrogen Oxygen Secondary Stage (HOSS), a precursor to the Centaur.

- Fairing Base
- Upper Stage
- Interstage
- Medium 1.25m to 0.9375m Structural Adapter
- Short 1.5m to 1.25m Structural Adapter
- Upper Tank (LT/ELT config)
- Lower Tank (Basic/LT; Ribbed config)
- Engine Fairing
- Verniers x2
- LR79-NA13

![Delta 904 Sketch](https://user-images.githubusercontent.com/12999059/88927991-2ceb2700-d270-11ea-90ad-da7ba83839e8.png)

_Delta 904_

Variants | First Stage | Boosters | Second Stage | Third Stage |
-- | -- | -- | -- | --
Thorad-Agena SLV-2G | LR79-NA13 | 3x Dioscuri 2 | Belle Interstage; Belle-D Upper Stage |
Delta L | LR79-NA13 | | Daleth E Upper Stage | Staara-20-IIA SRM 
Delta M | LR79-NA13 | | Daleth E Upper Stage | Staara-37B (Burner 2)
Delta N | LR79-NA13 | | Daleth E Upper Stage |
Delta M6, N6 "Super Six" | LR79-NA13 | 6x Dioscuri 2 | Daleth E Upper Stage |
Delta 300/900 | LR79-NA13 | 3/9x Dioscuri 2 | Daleth F Upper Stage |
Delta M HOSS | LR79-NA13 | 3x Dioscuri 1 or Algol II + 3/6x Dioscuri 2 | Daleth-K Interstage (Short); CUSS Upper Stage

- Daleth F Upper Stage = Daleth-E-210 Fuel Tank; JA10-118-F10 "Hebel" Engine
- CUSS (HOSS) Upper Stage = CUSS-1300 Fuel Tank; Inon-R-10A "Isor" Engine (Inon-R-10A Config)

![Agena D   HOSS Adapters](https://user-images.githubusercontent.com/12999059/70659623-6119c500-1c58-11ea-8f60-11f65c29c12f.png)

### Extended Long Tank Thor
Delta 1000 series combines an extended first stage tank with a new Delta P second stage and an 8-foot diameter payload fairing giving it the nickname "Straight-Eight."  Later variants of ELTT introduce the RS27 engine, Delta K second stage and upgraded Castor IV Solid Rocket Boosters.  Refer to the [Delta numbering scheme](https://en.wikipedia.org/wiki/Delta_(rocket_family)#Delta_numbering_system) for details of the naming convention.  The 2000 series onwards started to introduce the distinctive blue colour to the rocket.

- Fairing Base
- Upper Stage
- Daleth-K Interstage
- Upper Tank (LT/ELT config)
- Lower Tank (ELT; Ribbed config)
- Engine Fairing
- Verniers x2
- RS-27

![Delta 3920 PAM-D Sketch](https://user-images.githubusercontent.com/12999059/88928042-3d030680-d270-11ea-96ca-c0e58a36ec3f.png)

_Delta 3920 PAM-D_

Variants | First Stage | Boosters | Second Stage | Third Stage |
-- | -- | -- | -- | --
Delta 1910 'Straight Eight' | LR79-NA13 | 9x Dioscuri 2 | Daleth P |
Delta 2914 | RS-27 | 9x Dioscuri 2 | Daleth P | Staara-37D
Delta 3920 PAM-D | RS-27 | 9x Dioscuri 4 | Daleth K | Staara-48B PAM-D
Delta 4000 series | LR79-NA13 | Dioscuri 4A | Daleth K | Staara-48B
Delta 5000 series | RS-27 | Dioscuri 4A | DalethK |

- Daleth P Upper Stage = Daleth-P-180 Fuel Tank; RW-ATR2201 "Lysenko" Engine
- Daleth K Upper Stage = Daleth-K-240 Fuel Tank; JA10-118-K11 "Noshem" Engine

### Delta II (Extra Extended Long Tank Thor)
Delta II stretches the main tank even further with an uprated RS-27A engine.  The 7000 series employs the more powerful GEM-40 boosters or GEM-46 for the 'Heavy' variant.

- Fairing Base
- Upper Stage
- Daleth-K Interstage
- Upper Tank (EELTT)
- Lower Tank (EELT; Ribbed)
- Engine Fairing (Delta)
- Verniers x2
- RS-27A

![Delta II-7925](https://user-images.githubusercontent.com/12999059/88928090-4a1ff580-d270-11ea-8557-6c7706334a93.png)

Variants | First Stage | Boosters | Second Stage | Third Stage |
-- | -- | -- | -- | --
Delta 6920 | RS-27A | 9x Dioscuri 4A | Daleth K |
Delta 7925H | RS-27A | 9x GEM-46 | Daleth K | Staara-48B

### Delta III
Delta III accommodates bigger and heavier satellites by replacing both lower-performance upper stages with a single cryogenic secondary stage.  The first stage upper tank is widened and shortened to keep the overall height down.

- Fairing Base
- DCSS Upper Stage
- DCSS Interstage
- Delta III Upper Tank
- Lower Tank (Delta III)
- Engine Fairing (Delta)
- Verniers x2
- RS-27A

![Delta III-8940 Sketch](https://user-images.githubusercontent.com/12999059/88928137-5b690200-d270-11ea-88f0-bb6d9309d4e6.png)

Variants | First Stage | Boosters | Second Stage | Third Stage |
-- | -- | -- | -- | --
Delta 8000 | RS-27A | 9x GEM46 | DCSS RL10B-2 |

### Delta IV
Delta IV uses a Delta Cryogenic Secondary Stage on top of a widened 5m (3.125m KSP) Common Booster Core (CBC) powered by an RS-68 cryogenic engine.  The Delta IV Small proposition would have used a single CBC, a Delta II second stage and an optional Star 48B third stage inside a Delta II payload fairing.  Delta IV Medium (technically Delta 9040) has a modified Delta III second stage topped by a 4m or 5m fairing and adds 2, 4 or 8x GEM-60 SRBs on the  Delta IV Medium+.  Delta IV Heavy (Delta 9250H) uses 2 strap on CBC's in place of the SRB's.

Variants | First Stage | Boosters | Second Stage | Third Stage |
-- | -- | -- | -- | --
Delta IV M | RS-68 |  | DCSS-4 RL10B-2 |
Delta IV M+ (4,2) | RS-68A | 2x GEM-60 | DCSS-4 RL10B-2 |
Delta IV M+ (5,4) | RS-68A | 4x GEM-60 | DCSS-5 RL10B-2 |
Delta IV H | RS-68A | 2x CBC  | DCSS-5 RL10B-2 |

Place the radial decouplers in 2x symmetry then add the CBC's individually so the raceways and pipes all face the same way.  Switch on the side node on the Upper Liquid Fuel Tank to attach it to the decoupler.

![front_Delta IV H_1](https://user-images.githubusercontent.com/12999059/93375088-85da4300-f84f-11ea-86ed-b9918da16d71.png)

![Delta IV Pencil](https://user-images.githubusercontent.com/12999059/93439680-c1642400-f8c6-11ea-8022-52c48a686e19.png)

_Delta IV M, Delta IV M+ (5,2) & Delta IV H_

**Comment by friznit** [comment]
**Thor Tanks**
S = Short Tank (360)
L = Long Tank (880)
XL = Extra Long Tank (2700)
SA = Short Adapter Tank (380)
LA = Long Adapter Tank (860)

**Thor-Delta (S, L, SA)**
Delta A,B,C,C1 (Thor Able) = S,L,SA + Able
Delta D (TAD) = S,L,SA + 3x Castor I + Able
Delta E,F,G,H (TAID) = S,L,SA + 3x Castor II + Ablestar
Delta J?

**Long Tank Thor (S,L,LA)**
Delta M = S,L,LA + Ablestar?
Delta N "Super Six" = S,L,LA + 6x Castor II + Delta E (same as Ablestar?) + Star-37
Delta 904 = S,L,LA + 9x Castor II + Delta E + Star-37

**Extended Long Tank Thor (S,XL)**
Delta 1000 "Straight Eight" = S,XL + 9x Castor II + Delta P + Star-73
Thorad-Agena = S,XL + 3x Castor II + Agena D

**Comment by CobaltWolf** [comment]
**Upper stages:**

- Able / Delta (Thor-Able/Delta/Delta A) = AJ10-37 Able Engine (Lower Performance Switch), Thor Able Guidance Unit, 0.625m Fairing Base.  Technically this is Delta upper stage cos it has RCS.
- Delta B (Delta B/C/C1/D) = AJ10-118D Able Engine (Higher Performance Switch), Stretched Tank, Thor Able Guidance Unit, 0.625m Fairing Base
- Able-Star (Thor Able-Star) = AJ10-104 Ablestar Engine (Lower Performance Switch), Ablestar Tank, 0.9375m Fairing Base (basically a fat Able)
- Delta E (Delta E-N) = AJ10-118E Ablestar Engine (Higher Performance Switch), Delta E TAID Tank, 0.9375m Fairing Base
- Delta F (300/900/1000 series) = AJ10-118F, Delta E TAID Tank, 0.9375m Fairing Base
- Delta P (191x/2x1x/391x) = TR-201 Engine, Delta P Tank, Delta P Fairing, Delta K Avionics Block
- Delta K (3-7k series) = AJ10-118K Engine, Delta K Tank, Delta P Fairing, Delta K Avionics Block
- HOSS = RL10-A Engine, HOSS Engine Mount, HOSS Tank, 1.5m Fairing Base
- Agena A (Thor-Agena A)
- Agena B (Thor-Agena B)
- Agena D (Thor-Agena D; TAT Agena, Thorad-Agena D)

Agena D HDA
8096B
8096C

http://www.b14643.de/Spacerockets_2/United_States_4/Agena/index.htm

![image](https://user-images.githubusercontent.com/12999059/70167573-f21ff780-16be-11ea-82f1-d4e07105ada3.png)

**Comment by CobaltWolf** [comment]
![image](https://user-images.githubusercontent.com/12999059/67814055-03ac2900-fa9b-11e9-8272-35f03034c539.png)

![image](https://user-images.githubusercontent.com/12999059/67846255-ce362880-faf8-11e9-99e1-b5a55107e9a3.png)

![image](https://user-images.githubusercontent.com/12999059/68965303-60b21980-07d3-11ea-9bcd-26ca1143144a.png)

**Comment by CobaltWolf** [comment]
**Thrust Augmented Improved Delta:**

Delta E: 3x Castor 1s, LT, L125T, 9A, 9I, Delta E, Altair
Delta J: 3x Castor 1s, LT, L125T, 9A, 9I, Delta E, Star-37B (the spherical one)

**Long Tank Thor Delta:**

Delta L: 3x Castor 2s, LT, UT, S125A, 9A, 9I, Delta E, Altair
Delta M: 3x Castor 2s, LT, UT, S125A, 9A, 9I, Delta E, Star-37B
Delta N: 3x Castor 2s, LT, UT, S125A, 9A, 9I, Delta E, no kick solid
Delta M6: 6x Castor 2s, LT, UT, S125A, 9A, 9I, Delta E, Star-37B
Delta N6: 6x Castor 2s, LT, UT, S125A, 9A, 9I, Delta E, no kick solid

Delta 300: 3x Castor 2s, LT, UT, S125A, 9A, 9I, Delta F, no kick solid
Delta 900: 9x Castor 2s, LT, UT, S125A, 9A, 9I, Delta F, no kick solid

**Comment by friznit** [comment]
WIP

**Thor-Delta**
Generic build = LR79, Engine Fairing & Verniers, Base Tank, Adapter Tank, Upper Stage Adapter, Interstage Decoupler, Upper Stage Assembly, Fairing

LV | First Stage | Boosters | Second Stage | Third Stage |
-- | -- | -- | -- | --
Thor-Able       | LR79 (fins) | | Able, Able Adapter, Thor Able Interstage |  |
Thor-Ablestar | LR79 (no fins) | | Ablestar, Medium Adapter, Thor Interstage |  |
Delta C            | LR79 (fins) | | Delta B, Medium Adapter, Thor Delta Interstage | Star 20 Altair  (Opt) |
Delta D (TAD) | LR79 | 3x Castor 1 | Delta B, Medium Adapter, Thor Delta Interstage | Star 20 Altair  (Opt) |
Delta J (TAID) | LR79 | 3x Castor 1 | Delta E, Medium Adapter, Thor Interstage  | Star-37B |

**Long Tank Thor Delta**
Generic build = LR79, Engine Fairing & Verniers, Base Tank, Upper Tank, Upper Stage Adapter, Interstage Decoupler, Upper Stage Assembly, Fairing

LV | First Stage | Boosters | Second Stage | Third Stage |
-- | -- | -- | -- | --

Delta M6 'Super Six' (LTT) | LR79 | L U | 125A, 9A | TI | Delta E/F | Star 20 / Star 37B | 3/6/9x Castor 2
Thorad Agena | LR79 |   |   |   | Agena D |   | 3x Castor 2
Delta 3915 'Straight Eight' (ELTT) | RS-27 |   |   |   | Delta P | Star-48 PAM | Castor 4
Delta II 7925 (EELTT) |   |   |   |   |   |   |  
Delta III 8930 |   |   |   |   |   |   |  

Thor Agena
Burner 2
Thorad-Agena SLV-2G/H (LTTAT)

**Comment by friznit** [comment]
**Builds Guides**
Thor Delta
- [x] Thor Able (Full guide)
- [x] Thor Agena A (interstage)
- [x] Delta D & J (interstage)

LTT
- [x] Delta 904 (open sketch)
- [x] Thorad Agena D
- [x] Agena & HOSS (interstage)

ELTT
- [x] Delta 3920 PAM D (open sketch) - _pending Castor IV update_

**Upper Stages**
- [x] Able
- [x] Delta B
- [x] Ablestar
- [x] Delta E (TAID)
- [x] Delta F
- [x] Delta P
- [x] Delta K
- [x] HOSS (Proposed for Delta M)
- [x] Agena A
- [x] Agena B
- [x] Agena D

**Blueprints**
- [x] Thor Delta Line Up

**Comment by friznit** [comment]
Builds guides for

Thor Able (Full guide)
Delta D & J upper part only open sketch
Delta 904 - open sketch
Delta 3920 PAM D - open sketch

**Comment by friznit** [comment]
**ETS Things**
ETS Centaur E == Centaur T == Centaur G'

Delta 4000 = 1.875m core; 0-12x Castor IV; 3x H-1D; Centaur D
Delta 5000 = above but GEM-40

**Comment by friznit** [comment]
![Thor Able Build Guide](https://user-images.githubusercontent.com/12999059/84049630-95bacf00-a9a4-11ea-9147-b96046432bb4.png)
Thor-Able.  Thor-Delta is a similar build except the upper stage uses the longer _Thor Able II 120 Liquid Fuel Tank_ and the Thor Able Interstage part switch is set to _Delta_.

![Delta B E Adapters](https://user-images.githubusercontent.com/12999059/70659602-54956c80-1c58-11ea-8bc7-6bdb5079c871.png)

![Agena D   HOSS Adapters](https://user-images.githubusercontent.com/12999059/70659623-6119c500-1c58-11ea-8f60-11f65c29c12f.png)

![Delta 904 Sketch](https://user-images.githubusercontent.com/12999059/68531998-72497c00-0310-11ea-9008-da3753f64e0f.png)

_Delta 904_

![front_Delta 1910 OSO8_1](https://user-images.githubusercontent.com/12999059/68531947-e59ebe00-030f-11ea-8677-a4226fb2de18.png)

_Delta 1910 OSO8 (1975)_

![Delta 3920 PAM-D](https://user-images.githubusercontent.com/12999059/72462146-49d67600-37c8-11ea-927a-5be042a990b6.png)

_Delta 3920 PAM-D_

![image](https://user-images.githubusercontent.com/12999059/75635036-c1425680-5c0a-11ea-8cc2-f3400a562350.png)

_Keyhole Evolution_

**Comment by friznit** [comment]
![Able-Delta-Delta B Upper Stage](https://user-images.githubusercontent.com/12999059/68544825-ef332f00-03be-11ea-94d8-223bad83db58.png)

_Able/Delta & Delta B_
Technically the left is a Delta upper stage as it has the integrated RCS.

![Ablestar Upper Stage](https://user-images.githubusercontent.com/12999059/68544850-1db10a00-03bf-11ea-806a-9833f4116564.png)

_Able-Star_

![Delta E-F Upper Stage](https://user-images.githubusercontent.com/12999059/68544857-24d81800-03bf-11ea-8ed4-90102c6a581d.png)

_Delta E & F_

![Delta P-K Upper Stage](https://user-images.githubusercontent.com/12999059/68544864-2b668f80-03bf-11ea-84d4-c605d92daf05.png)

_Delta P & K_

![Agena Upper Stages](https://user-images.githubusercontent.com/12999059/70659629-6414b580-1c58-11ea-9692-e9de4e72e067.png)

_Agena A, B & D (later variants of Agena B also use 8096 Engine)_

![front_Agena SOTS Upper Stage_1](https://user-images.githubusercontent.com/12999059/88390209-d4b7af00-cdaf-11ea-8ad9-561b1f7c35d4.png)

_Shuttle/Agena Upper Stage (Agena SOT)_ was a concept study for a re-usable space tug on the Shuttle.  Take an Agena D, add 6 to 8 strap-on drop tanks (SOT), a modified engine and a helical antenna for long range comms.


![HOSS Upper Stage](https://user-images.githubusercontent.com/12999059/68545198-9b2a4980-03c2-11ea-8f36-52f4440069c0.png)

_HOSS_
Hydrogen Oxygen Second Stage considered for Delta M upgrade with combinations of different SRBs (3x Castor 1 or Algol II plus 3/6x Castor 2);   0.938m or 1.875m fairing (from Titan 23C).

**Comment by friznit** [comment]
**Vanguard**
Vanguard TV-3 (Test Vehicle 3) = launch failed
Vanguard 1 (TV-4; Star 20 GC 33-KS-2800 Config) = Easton-V1 "Narly" Probe Core
Vanguard 2 (SLV-4) = Easton-V2 "Narly" Probe Core
Vanguard 3 (SLV-7; Star 20 X-248 Config) = Easton-V3 "Narly" Probe Core

|Launch Vehicle|First Stage|Second Stage|
|---|---|---|
|Vanguard TV-3| |Staara-20-II-A SRM (33-KS-2800 Config)|
|Vanguard TV-4| |Staara-20|
|Vanguard SLV-4| |Staara-20|
|Vanguard TV-7| |Staara-20 (X-248 Config)|

![Vanguard SLV-7](https://user-images.githubusercontent.com/12999059/81665288-729a0f80-9438-11ea-8e8b-5b9ade8d7d71.png)

**Comment by CobaltWolf** [comment]
Vanguard should use the black second stage

**Comment by friznit** [comment]
> Vanguard should use the black second stage

This is SLV-7 with Vanguard 3 - the SLV's from 5+ had a white second stage. [ Image reference here](http://www.b14643.de/Spacerockets_2/United_States_7/Vanguard/Gallery/Vanguard.htm)

**Comment by CobaltWolf** [comment]
Good catch then - I've been assuming that people were most interested in the TV-4 since that was the first successful launch. Good to know the rest of the paint schemes are buildable.

**Comment by friznit** [comment]
![front_Agena A Upper Stage_1](https://user-images.githubusercontent.com/12999059/69828124-78958e80-1212-11ea-8cd2-a66a63d37b68.png)

**Comment by Morphisor244** [comment]
Vanguard is supposed to use a spin decoupler, but it's not shown in the diagram?

**Comment by friznit** [comment]
> Vanguard is supposed to use a spin decoupler, but it's not shown in the diagram?

There are no decouplers at all in the diagram (hopefully it should be pretty obvious they're needed). 
 Sadly the spin decoupler doesn't work as intended in game and afaik won't be added to the release because it'd require some level of programming to do properly.  So to avoid confusion I've not included it in any build guides.

**Comment by friznit** [comment]
Check Delta dimensions
Document proc fairing settings

**Comment by Morphisor244** [comment]
Minor nitpick: the Vanguard diagram shows the Staara-20 in X-258 config, which is incorrect. It should either be the initial Grand Central config or the X-248 config (vanguard 3 only).

**Comment by zorg2044** [comment]
Oh also worth noting the spin decouplers all work now.

**Comment by friznit** [comment]
Added to the To Do list!

**Comment by JoeSheridan2** [comment]
> **ETS Things**
> ETS Centaur E == Centaur T == Centaur G'
> 
> Delta 4000 = 1.875m core; 0-12x Castor IV; 3x H-1D; Centaur D
> Delta 5000 = above but GEM-40

I have looked onto the technical data for the ETS Delta 5000 series: 
https://www.alternatehistory.com/wiki/doku.php?id=timelines:eyes_turned_skyward_spacecraft_and_launch_vehicle_technical_data
and when i compare it with the GEM-Motor-Series i see that the GEM-46 fits better than the GEM 40´s.... but even they are a little to light weight in comparison to the ETS CCM 46´s (GEM-46 Prop mass: 16,860 kg (37,180 lb) vs CCM-46´s 17,010 kg) but that´s absolute okay for a fictional kitbash rocket :) It´s just that the real life 40´s are more than 6 Tons to light... not only 200 kilograms.

**Comment by OrbitalManeuvers** [comment]
The Easton RSMs seem wonky to me. First, the thrust comes out the same direction that the cone tapers/points, as of 9/3. So, in the picture above, the upper stage will be pushed retrograde down onto the lower stage at separation. To me, the part visually looks like "pointy end = aerodynamic so face the wind, flat end = thrust comes out" ... which would mean building as seen above. However that's not how the part currently works. The text description in the part is a bit confusing as well. As of today, if you want to use them to "carry the upper stage away" like the text says, you'll need to flip em vertically.

Seems like something is maybe reversed somewhere? Could be just the wiring in my head.

**Comment by CobaltWolf** [comment]
> 
> 
> The Easton RSMs seem wonky to me. First, the thrust comes out the same direction that the cone tapers/points, as of 9/3. So, in the picture above, the upper stage will be pushed retrograde down onto the lower stage at separation. To me, the part visually looks like "pointy end = aerodynamic so face the wind, flat end = thrust comes out" ... which would mean building as seen above. However that's not how the part currently works. The text description in the part is a bit confusing as well. As of today, if you want to use them to "carry the upper stage away" like the text says, you'll need to flip em vertically.
> 
> Seems like something is maybe reversed somewhere? Could be just the wiring in my head.

Pointy end goes up. They had an aerodynamic cap on them. 

http://www.accur8.com/images/vanguardplan2.jpg

**Comment by OrbitalManeuvers** [comment]
OK cool. But like ... fire and venom is coming out that end, so how would that work on the upper stage?

**Comment by OrbitalManeuvers** [comment]
for reference: https://i.imgur.com/BJ46lbz.png

**Comment by friznit** [comment]
> OK cool. But like ... fire and venom is coming out that end, so how would that work on the upper stage?

Presumably because the retros are there to move the upper stage away at payload separation, unlike ullage motors on other rockets that are designed to settle the fuel tank before secondary stage ignition.

**Comment by OrbitalManeuvers** [comment]
OK ... what have I done wrong here:
https://youtu.be/6eKpcUmpnWE   .

**Comment by OrbitalManeuvers** [comment]
OK - it's timing, right? You're using those motors after the payload separation not at stage sep?

**Comment by friznit** [comment]
> OK - it's timing, right? You're using those motors after the payload separation not at stage sep?

Yes, put them in the same stage as the payload decoupler - they push the payload away and the spin decoupler spins up.

**Comment by OrbitalManeuvers** [comment]
the brain freeze has been real, but it's thawing. thanks for the explanation.

**Comment by OrbitalManeuvers** [comment]
Thor-Able picture:  my "Fenris-1400/2040/2600 Lower Fuel Tank" does not have two horz stripes near the bottom when set to Able paint job and Basic length, so I'm guessing here ... but I think after that tank you have the "Fenris-Daleth Engine Fairing" which is not mentioned in the text.

**Comment by friznit** [comment]
> Thor-Able picture: my "Fenris-1400/2040/2600 Lower Fuel Tank" does not have two horz stripes near the bottom when set to Able paint job and Basic length, so I'm guessing here ... but I think after that tank you have the "Fenris-Daleth Engine Fairing" which is not mentioned in the text.

Good spot - fixed!
