### ISSUE TITLE
Modular Launch Pad Builds

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#24]
Since AlphaMensae is amenable, and KerbalKore asked....

TLC-19: Titan II
TLC-34: Saturn I Milkstool
TLC-40: Titan III, Titan IV, SpaceX Falcon 9
TLC-41: Titan III, Titan IV, Atlas V
TLC-46: Minotaur
TSC-39A: Saturn V
TSC-39A: Space Shuttle
TSC-39B: Saturn IB
TSC-39B: SLS

**Comment by svcino** [comment]
TLC-40: Titan-3 series and Titan 4
TLC-41: Titan-3 series,Titan 4 and atlas V
