### ISSUE TITLE
Homepage revamp

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#26]
More pics, fewer words.  So may words....

Icons?
128x128
Corner 20
Hex 383838
Pencil Sketch Tip 4 / Range 10
Consolar 12 Bold

```
[![Image](yourImage.jpg)](http://your Link Here.com "Description")

[Link Text](full-URL-of-wiki-page)
```
[![Icon_Thor](https://user-images.githubusercontent.com/12999059/64560768-15960900-d341-11e9-841f-ec7aabcbbed3.png)](https://github.com/friznit/Unofficial-BDB-Wiki/wiki/Thor "Thor")

Redo:

Titan
Saturn V
Saturn MLV
AORV

**Comment by friznit** [comment]
[[Link Text|nameofwikipage]]

[[![image](https://user-images.githubusercontent.com/12999059/64486656-97920f00-d227-11e9-94da-91d912a14254.png)|Titan]]

**Comment by CobaltWolf** [comment]
omg Icons are so cool
