### ISSUE TITLE
MOL Update

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#28]
Base 'official definitive' MOL design - not sure this is correct, seems to be missing the unpress part
![front_MOL_1](https://user-images.githubusercontent.com/12999059/66668126-62c10f80-ec4c-11e9-96aa-39d2040cca7d.png)

Some alternative designs based on available documentation and maybe one 'gameplay' koncept?

In launch configuration on Titan IIIM
![front_Titan IIIM MOL_1](https://user-images.githubusercontent.com/12999059/66668160-7d938400-ec4c-11e9-94a5-2b70abf5b38f.png)

Koncepts: Modular MOL Space Station to show off the other parts.  Maybe do an exploded view?
![Cobalt X](https://user-images.githubusercontent.com/12999059/66668149-71a7c200-ec4c-11e9-89cc-397dcbc6a654.png)

**Comment by CobaltWolf** [comment]
Yup! Hold off a little bit more on it, there's still some stuff missing.

**Comment by friznit** [comment]
What is the definitive 'official' MOL design?

**Comment by CobaltWolf** [comment]
The one I sent you.

**Comment by CobaltWolf** [comment]
The unpressurized segment is for alternate configurations. And MOL didnt fly with Transtage like a lot of people think.
