### ISSUE TITLE
Kerbal Koncepts

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#3]
Add wiki category for the weird, the wonderful and the whacky ideas that have been proposed over the years and can be built using BDB.  Add any others you run across below!

- [x] [Alliant Systems EELV](https://forum.kerbalspaceprogram.com/index.php?/topic/122020-16x-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v152-%D0%B1%D1%80%D1%83%D0%BD%D0%BE-8feb2019/&do=findComment&comment=3628396)

- [x] [MDD Barbarian](https://en.wikipedia.org/wiki/McDonnell_Douglas_Barbarian)

- [x] [Juno V/Saturn A-1](https://en.wikipedia.org/wiki/Juno_V) US Army's early plan for crewed lunar lander

- [x] [Lunex](https://en.wikipedia.org/wiki/Lunex_Project) USAF's plan for crewed lunar lander.

- [x] [Saturn C-8](https://en.wikipedia.org/wiki/Saturn_C-8), NASA design for Apollo Earth Orbit Rendezvous mission concept but rejected in favour of the smaller Saturn V and a Lunar Orbit Rendezvous mission profile.

- [x] ~[Nova](https://en.wikipedia.org/wiki/Nova_(rocket)) post-Apollo concepts for Mars missions.  Nova was almost identical to Saturn C-8.~

- [x] [Jarvis](http://www.astronautix.com/j/jarvislaunchvehicle.html) S1 35x8.38m 2x F-1; S2 10x8.38m 1x J-2; S3 3x5.2m 8x R-4D

- [x] [SRM/CORE-2](https://www.spacelaunchreport.com/SRM-Core2-Card.jpg) Titan "stick": S1 UA-1205; S2 Titan 3 LR-91-11; S3 Agena D/Centaur D-1T/Star-37 Burner 2.

- [x] [Titan 3BAS2](https://www.spacelaunchreport.com/Titan-3BAS2-Card.jpg) Augmented Titan 3B Centaur: S1 2x LR87-11 + 2x Algol 2 SRB; S2 Titan 3 LR-91-11; S3 Centaur D1-T; S4 Optional Burner 2.

- [x] [Fatlas SLV-X Centaur D](https://www.spacelaunchreport.com/atlasnot.html) 2x MA-5 boosters; 1x H-1D sustainer; Centaur D 2x RL10A3;  Interstage roll control replaces verniers.

- [x] Athena IIcS; S1 Castor 120 + 2/4/6 Orion 50SX SRB; S2 Castor 120; S3 Castor 30; S4 OAM; 3.1m Fairing

- [x] [ETS Carrack](https://www.alternatehistory.com/wiki/doku.php?id=timelines:eyes_turned_skyward_media#nixonshead_s_artworks) S0 0/2/4x Castor-120; S1 Castor-120; S2 Castor 120; S3 Agena D; 2.34m or 3.5m fairing.

- [x] [Saturn MLV-V-4(S)-A](https://forum.kerbalspaceprogram.com/index.php?/topic/122020-16x-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v152-%D0%B1%D1%80%D1%83%D0%BD%D0%BE-8feb2019/&do=findComment&comment=3677357) S1 MS-IC 4xUA1205  S2 MS-IIA S3 MS-IVC

- [ ] [Nova MM 1C](http://www.astronautix.com/n/novamm1c.html)

- [ ] [Saturn Mk2](https://ntrs.nasa.gov/citations/20120013881)

- [ ] [Double Barrel Delta](https://forum.nasaspaceflight.com/index.php?PHPSESSID=map2gihsdd4mmbh062vhjke154&action=dlattach;topic=40733.0;attach=1415931;image)

- [ ] Comet HLLV

- [x] MORL & stretched Gemini ferry/supply spacecraft

**Comment by CobaltWolf** [comment]
re: Athena IIcS, the closest motor in BDB is the Castor IV radials. The way they worked IRL is they don't separate - instead they and the Castor 120 are tuned to have identical burn times. Basically it acts less like a Stage 0 or strap-on boosters, and more like a direct augmentation of the Castor-120

**Comment by friznit** [comment]
SII INT 19 Algol SRB is close enough to Minuteman.

**Comment by longlong2002** [comment]
one typo error Castor 12 not castor-120 and castor-30

**Comment by friznit** [comment]
![front_Gemini Space Station Prog C_1](https://user-images.githubusercontent.com/12999059/91449332-e12d9c80-e872-11ea-8027-45ec1130bf30.png)

[Gemini Space Station - Program C](https://spaceflighthistory.blogspot.com/2015/12/space-station-gemini-1962.html)

**Comment by onyxx72** [comment]
Nice

**Comment by mountainparrot** [comment]
Athena III?
