### ISSUE TITLE
RL10s and Centaur

### ISSUE THREAD

**Issue by zorg2044** [friznit/Unofficial-BDB-Wiki#31]
Just trying to make sense of the various RL10s and to which Centaur they correspond to. 

### The RL10s
1) RL10 A model with fixed nozzle has 3 B9 subtypes linked to part upgrades
- RL10-A-1 (prototype that flew on Centaur A)
- RL10-A-3 operational model
- RL10-A-4 further improvements

2) RL10-A-4-1N extending nozzle

3) RL10-B-2 bigger extending nozzle

### The Centaurs
- Centaur D
First operational Centaur, 2x RL10-A-3

- Centaur D1
Also 2x RL10-A-3

- Centaur G/T
2x RL10-A-3
2x RL10-A4 (Centaur T upgrade)

- Centaur II (D2)
(D2)               2x RL10-A3 (early version, could ignore in the wiki)
(D2A)            2x RL10 A4
(D2-A-1-N)    later upgraded to 2xRL10-A4-1N with the nozzle extension
(D3A)              Centaur II was briefly used on early Atlas III. 1x RL10-A4-1N

- Common Centaur (aka Centaur III aka D3B for Atlas III and D5for Atlas V)
1 or 2x RL10-A-4-1N
(irl the Atlas V used the A-4-2N which had a fixed rather than deploying extension but BDB only has the deployable model)

Suggestions for the wiki
- Change references to match the right part/subtype. right now the fixed nozzle one is abstracted into just RL-10A
- Centaur D1 and Centaur III have the wrong RL10 in the descriptions. See above.
- This line in the description for Centaur III is incorrect, "Like Centaur II, Centaur III can use either one RL10-C (Single Engine Centaur) or two RL-10-A (Dual Engine Centaur) engines."

RL10 C is a suffix being used for a whole new series of RL10s being developed that succeed the A4-1 and B-2. It has no bearing on whether its single or dual. In any case these parts arent in BDB. 

http://www.b14643.de/Spacerockets_2/United_States_3/Atlas-Centaur/Gallery/Tab.jpg

http://www.b14643.de/Spacerockets/Specials/P&W_RL10_engine/Evolution.gif

**Comment by friznit** [comment]
Updated

**Comment by zorg2044** [comment]
Hmm so this shows Centaur T with both RL10-A3 and RL-10A4-1 (without the nozzle extension so lets call it RL10-A4 in BDB).

Centaur G being an earlier design would have been RL10-A3 of course although if it had been made Im sure it would have gotten the upgrade.

If you wanted to keep it simple I reckon just put down RL10-A4

http://www.b14643.de/Spacerockets_2/United_States_6/Titan_IV/Description/Frame.htm
