### ISSUE TITLE
Additional Build Guide Diagrams

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#32]
Add build guides for some rockets that are still not fully clear how to build

- [x] Titan 23B upper stage split sketch

**Comment by friznit** [comment]
### Non BDB

- [x] H-I
S1: 1x MB-3 on Thor ELT (as per Delta 1K); 6-9x Castor 2
S2: 1x LE-5

- [x] H-II

H2A wxyz
w = # stages
x = LRBs
y = SRBs (SRB-A)
z = SSB Solid Strap On Booster (Castor 4A-XL)

- [x] H-IIA 202 Zorgbash:

First Stage (2.5m dia)
- 2x BDB Castor 120 (SRB-A analogue)
- BDB BSF Thor Engine Fairing
- EP-25 Engine Plate
- 1x ReStock Skipper (LE-7A analogue) with CryoTanks LH2 patch
- 1m height Procedural Tank (intertank) (Green Basic Procedural Textures)
- 1x ReStock Jumob-64
- 1x ReStock X200-32
- 1m height Procedural Tank (intertank) (Green Basic Procedural Textures)
- 1x ReStock X200-32
- Decoupler shroud for interstage

Second Stage:
- BDB RL10 (Cryo; in place of LE-5B)
- BDB Vega centre tank and engine mount
- NFLV Truss (tweakscaled)
- 1x Restock 2.5m tank


- [x] H-IIB 

First Stage (3.25m dia) +1m higher
- BDB LDC 2x engine mount (Tweakscaled 2.5x)

- 4x SRB-A3
- 2x LE-7A

![image](https://user-images.githubusercontent.com/12999059/65714224-96b80480-e092-11e9-8c27-7e195a9a2c37.png)

- [x] H-III (3.25m dia)

- 0 - 4x SRB-3
- S1 2 or 3 LE-9 (CE CR-98 "Fuji")
- S2 1x LE-5B

**Comment by svcino** [comment]
antares request

**Comment by friznit** [comment]
> antares request

Already here: https://github.com/friznit/Unofficial-BDB-Wiki/wiki/Antares

Clearly needs more work but I ran out steam a bit because I couldn't find a suitable RD-181 analogue that worked.

**Comment by friznit** [comment]
H-II can also use DCSS upper stage

**Comment by svcino** [comment]
> > antares request
> 
> Already here: https://github.com/friznit/Unofficial-BDB-Wiki/wiki/Antares
> 
> Clearly needs more work but I ran out steam a bit because I couldn't find a suitable RD-181 analogue that worked.

Use RD180 instead
