### ISSUE TITLE
Saturn II and INT20, 21

### ISSUE THREAD

**Issue by zorg2044** [friznit/Unofficial-BDB-Wiki#33]
I was thinking it would be nice to have a note on HG3 engines within the page itself as right now its not very clear what the reference is. Can give a suggestion to the nearest equivalent in BDB as well as point to the dedicated HG3 engines in BDB extras if people want full authenticity.

I will update the HG3 configs in extras to the new engine balance soon as I can and also add it to the thrust buff patch too.

EDIT : Looks like the HG3 configs by pappystein used a multiplier on the base value. So those configs should be good. Just need to update the thrust buff patch.

------------------------------ already covered in MLV page, doh --------------

Not 100% sure if Int 20 and 21 are technically Saturn II but they were considered as part of the same study. An easy addition, Int21 is essentially S1C +SII and Int 20 is S1C (3-5x F1) + SIV-B.

Int20 S1C was studied with 3-5 F1 engines although only 3 and 4 are considered viable.

http://www.astronautix.com/data/satvint.pdf

(yes its astronautix but its a proper PDF :P )

from wikipedia which cites the above as reference:

"Using the original five-engine S-IC would require three engines to be shut down 88 seconds after launch, with the remainder of the first-stage flight flown on only two engines. This meant that a considerable amount of the firing time would be carrying three engines of "dead weight". As a consequence the extra payload over a four-engine variant would only have been about one thousand pounds, and the extra cost and complexity of the fifth engine was unjustified.

A four-engine variant would launch with four engines firing and shut down two engines 146 seconds after launch. The remaining two engines would burn until first-stage shutdown 212 seconds after launch. This variant could put approximately 132,000 pounds into a 100 nautical mile (185 km or 115 statute mile) orbit, versus around 250,000 pounds for the three-stage Saturn V.

The three-engine variant would burn all three engines up to first-stage shutdown at 146 seconds after launch. This variant could put approximately 78,000 pounds of payload into a 100 nautical mile (185 km) orbit, around twice the useful payload of the Saturn IB."

**Comment by friznit** [comment]
INT-20 and INT-21 are under Saturn MLV, which covers the wider post-Apollo applications programme, whereas Saturn II specifically focused on phasing out Saturn IB production lines.

Added an explicit not on HG-3 to make it more obvious where that is
