### ISSUE TITLE
Blueprints

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#34]
- Desaturate (remove colours)
- Edge detect (sobel)
- Desaturate again
- Blueprint background layer
- Layer mode screen

**Comment by CobaltWolf** [comment]
why is the logo upside down

**Comment by friznit** [comment]
> why is the logo upside down

You're holding the picture the wrong way up

**Comment by friznit** [comment]
![Saturn V_1_BP](https://user-images.githubusercontent.com/12999059/66151540-78f91b00-e60f-11e9-8d5b-814860577a86.png)

**Comment by friznit** [comment]
![BDBLineUpBP](https://user-images.githubusercontent.com/12999059/66228263-de640f00-e6d6-11e9-89f1-f01258de4bf6.png)
