### ISSUE TITLE
Atlas (Unflown) Updates

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#36]
Updates for

- [x] Vega
- [x] SLV-3X Fatlas
- [x] SLV-3K Fatterlas (pending new tapered tank)
- [x] CELV Obeselas

Which boosters do you want to show on the CELV?

**Comment by CobaltWolf** [comment]
Probably GEM-60XLs, if I remember they're the closest to what is described in the actual text that accompanies the image. 

Sorry for the lack of the tapered tanks, it will take a bit to get to them since I'm out of town this weekend.
