### ISSUE TITLE
ISS Page

### ISSUE THREAD

**Issue by ionenjoyer** [friznit/Unofficial-BDB-Wiki#41]
On [this](https://user-images.githubusercontent.com/12999059/69891282-59226280-12f3-11ea-8175-e82541c5bd30.png) image, I believe that Kibo and Colombus, Quest and Node 3 are on the wrong sides.

**Comment by friznit** [comment]
Actually the whole image is mirrored so it's all backwards.  It's a bit of a rush job as a place holder.  I've not decided what images to use yet.
