### ISSUE TITLE
Redstone Update

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#42]
**Etoh (Jupiter)**

- [x] Jupiter-A
- [x] Jupiter-C (Juno I) Build Guide (add decoupler to enable spinny things)
- [x] Mercury-Redstone Launch Vehicle
- [x] SPARTA WRESAT Build Guide
- [x] Sergeant (Upper Stages)

**Comment by friznit** [comment]
![front_Jupiter-A_Sketch](https://user-images.githubusercontent.com/12999059/70802868-90d8e200-1daa-11ea-84b9-91bf03a0d8a5.png)
_Jupiter A_

![front_Jupiter-C_2](https://user-images.githubusercontent.com/12999059/85875528-3e05cb80-b7cc-11ea-9dc4-f06c17470b7f.png)
_Juno I (Jupiter-C derived) & Mercury Redstone Launch Vehicle_
(Note: attach fins individually and match up the paint scheme with the engine mount)

![front_SPARTA WRESAT_2](https://user-images.githubusercontent.com/12999059/70802920-b36afb00-1daa-11ea-8a9f-763cd14cc8d0.png)
SPARTA WRESAT

![front_Sergeant_1](https://user-images.githubusercontent.com/12999059/85875538-452cd980-b7cc-11ea-8bea-b1df63a816a1.png)
Sergeant (with Juno I)

**Comment by CobaltWolf** [comment]
the only thing I'd note is that the Sparta should use the shorter "Redstone" tank and not the longer "Juno" tank (it looks like it's using the wrong one above)

**Comment by friznit** [comment]
Cool thanks - fixed

What goes on top of Jupiter-A?

**Comment by CobaltWolf** [comment]
I don't know what Jupiter-A is?

**Comment by friznit** [comment]
Redstone Missile 25 onwards.  It was officially renamed Jupiter-A at some point in 1955/56 depending on which source you go by (Army or Air Force). It was the first rocket to test Jupiter components, before Jupiter-C. https://www.spacelaunchreport.com/jupiter3.html

I'm guessing they look the same as the green  tactical Redstone missiles.  Can't really find any definitive pictures in colour of one flying as Jupiter-A.

![image](https://user-images.githubusercontent.com/12999059/70738858-7f8dc800-1d0d-11ea-9cd1-40c177026736.png)

![image](https://user-images.githubusercontent.com/12999059/70738911-9cc29680-1d0d-11ea-965a-042b5c9a732b.png)

**Comment by CobaltWolf** [comment]
I mean, not much to go off but Astronautix specifies that it tested new guidance and control systems primarily, so no it wouldn't be much of a visual different.

**Comment by KerbalKore** [comment]
Speaking of the redstone missiles, can we get a build guide for that?

**Comment by CobaltWolf** [comment]
No.

**Comment by zorg2044** [comment]
@friznit if the dock rotate option is used to make the spin table, a decoupler is needed above the nose cone. Otherwise the auto shroud of the sergeant cluster wont rotate.

**Comment by friznit** [comment]
OK.  It does not harm to include a decoupler in the standard build so I'll add it and then people have the option.

**Comment by Morphisor244** [comment]
Might be a good idea to add an updated mercury capsule build guide, the parts are all there by now I think?

**Comment by friznit** [comment]
> Might be a good idea to add an updated mercury capsule build guide, the parts are all there by now I think?

It's here: https://github.com/friznit/Unofficial-BDB-Wiki/issues/47#issuecomment-611005578

**Comment by OrbitalManeuvers** [comment]
A few nits/questions since I noticed this one is marked ready. My dev build is fairly recent but not literally today. But with what I have...
- in the sergeant breakout, the "HLR-VD03 Stack Separator" is actually called "DGR-VD03 0.3125m Decoupler" 
- in the Juno build, the "Etoh-TU" is called "Etoh-140-TU", and the two configs are 148 and 140, not 160 and 140.

Unless I'm too out of date or doing something otherwise dumb?

**Comment by friznit** [comment]
> A few nits/questions since I noticed this one is marked ready. My dev build is fairly recent but not literally today. But with what I have...
> 
> * in the sergeant breakout, the "HLR-VD03 Stack Separator" is actually called "DGR-VD03 0.3125m Decoupler"
> * in the Juno build, the "Etoh-TU" is called "Etoh-140-TU", and the two configs are 148 and 140, not 160 and 140.
> 
> Unless I'm too out of date or doing something otherwise dumb?

Things get updated when there's a balance pass and it's very likely I miss some of the details - thanks for spotting!  Have fixed.

**Comment by BlackBliz** [comment]
I am full of pictures of Jupiter-A!

!PGM-11_Redstone_CC-43_2](https://user-images.githubusercontent.com/69351918/182408262-df7ae4b8-59fb-4169-b353-6d4b70fd6e9a.jpg)
![Jupiter-A_CC-39_1](https://user-images.githubusercontent.com/69351918/182408274-8cfd0c93-c817-4a6f-a3d0-65ef6fdfbd9f.jpg)
![Jupiter-A_CC-35](https://user-images.g
![Jupiter-A_CC-14](https://user-images.githubusercontent.com/69351918/182408287-b9e48f47-c3a2-439c-a423-55c737acca6c.jpg)
![Jupiter-A_RS-19](https://user-images.githubusercontent.com/69351918/182408289-8d965635-89b8-44a1-8b69-948a004b1390.jpg)
![Redstone_irbm2_14mar56_01](https://user-images.githubusercontent.com/69351918/182408294-710f4a47-e2db-400f-a2cb-0b4e8fbc7569.jpg)
ithubusercontent.com/69351918/182408279-1f2fd2c7-3205-47e1-8346-8d40934e03eb.jpg)
![Jupiter-A_RS-25](https://user-images.githubusercontent.com/69351918/182408283-0bdfe8e2-ec78-4c0e-b73f-567a538bce09.jpg)
