### ISSUE TITLE
BDB Sat Reorg

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#43]
![BDBSats](https://user-images.githubusercontent.com/12999059/74614271-6a1e8b00-510e-11ea-9286-f4d1b87c4c2b.png)

### Sorted by LV
**Vanguard**
- [x] Vanguard 1 (BDB Easton-V1 Narly) - TV-4
- [x] Vanguard 2 (BDB Easton-V2 Narly) - SLV-4
- [x] Vanguard 3 (BDB Easton-V3 Narly) - SLV-7

**Scout**
- [x] Orbiting Frog Otolith - Scout B

**Juno**
- [x] Explorer 1 - Juno 1
- [x] Explorer 7/8/11/S45/S46 - Juno 2
- [x] Pioneer 3/4 - Juno 2

**Thor**
- [x] TIROS-1 - Thor Able
- [x] Pioneer 0/1/2 - Thor Able
- [x] Pioneer 5 - Thor Able
- [x] Courier 1A, 1B - Thor Ablestar
- [x] KH-1 Corona (Discoverer 1) (BDB Spyglass-1 Bloodhound) - Thor Agena-A
- [x] KH-4 Corona (BDB Spyglass-4 Cerveza) - Thor Agena-B/D (+/- TAT)
- [x] Alouette 2 (BDB Skylark) [dual launch with Explorer 31] - Thor Agena-B
- [x] Nimbus 1 (BDB Aeolus) - Thor Agena-B
- [x] OGO 2 - Thor Agena-D (TAT) (same model as OGO 1)

**Delta**
- [x] Telstar 1,2 - Delta B
- [x] Relay 1,2 - Delta B
- [x] [OSO ](https://space.skyrocket.de/doc_sdat/oso-1.htm)(BDB NON) - Delta D
- [x] Pioner 6/7/8/9 - Delta E
- [x] AIMP - Delta E
- [x] Biosat 1/2 - Delta G
- [x] Biosat 3 - Delta N
- [x] Nimbus 5 (BDB Aeolus) - Delta 900
- [x] Nimbus 7 (BDB Aeolus) - Delta 2910

**LTT**
- [x] KH-4B Corona - Thorad-Agena
- [x] Nimbus 4 (BDB Aeolus) - Thorad-Agena

**Atlas**
- [x] Pioneer P-1/3 - Atlas Able
- [x] OGO 1 - Atlas-LV3 Agena-B
- [x] Mariner 1& 2 - Atlas-LV3 Agena-B
- [ ] Mariner 10 - Atlas-SLV3D Centaur-D1A
- [x] Ranger Block 1 (Ranger 1/2) - Atlas-LV3 Agena-B
- [x] Ranger Block 2 (Ranger 3/4/5) - Atlas-LV3 Agena-B
- [x] Ranger Block 3 (Ranger 6-9) - Atlas-LV3 Agena-B
- [x] Luna Orbiter (BDB Kreuznach) - Atlas-SLV3 Agena-D
- [x] KH-7 Gambit (BDB Gamble) - Atlas-SLV3 Agena-D
- [x] Orbiting Astronomical Observatory 1 & 2 - Atlas-SLV3B
- [ ] Pioneer 12 - Atlas-SLV3D Centaur-D1AR

**Titan**
- [x] KH-8 Gambit (BDB Gamble-3) - Titan III(23/24)B Agena-D
- [x] IDCSP (BDB MOCA) - Titan IIIC
- [x] Helios (BDB Sonne) - Titan IIIE Centaur-D1T Star-37E

**Others**
- [x] Ranger Lander
- [x] Mariner B

**Comment by friznit** [comment]
![Keyhole](https://user-images.githubusercontent.com/12999059/72462221-75f1f700-37c8-11ea-92ab-f21464ff658d.png)

**Comment by CobaltWolf** [comment]
omg omg omg

**Comment by friznit** [comment]
![Keyhole](https://user-images.githubusercontent.com/12999059/72615495-bcf8fd00-392c-11ea-83df-7734c75bfd64.png)

**Comment by CobaltWolf** [comment]
I think that image is confusing because it makes it seem like the camera systems might fly separate? And that's only the case with the KH-7. I think the camera systems (excluding the exploded view on the left) should be shown attached to the Agena stages, like in this graphic. https://upload.wikimedia.org/wikipedia/commons/a/ad/U.S._RecSat_Big_Picture.jpg

**Comment by friznit** [comment]
Bleuurg, I'll have to redo it from scratch - not enough space!

**Comment by CobaltWolf** [comment]
:(

**Comment by friznit** [comment]
BDB is worth it though - got to be top quality!

**Comment by friznit** [comment]
### Keyhole Programme
The Keyhole (BDB Spyglass) family of optical reconnaissance satellites uses the Agena upper stage as a satellite bus.  The cameras have limited capacity and imagery is recovered using a Satellite Recovery Vehicle, nicknamed the "film bucket".  Keyhole satellites should be launched into a low altitude sun-synchronous orbit.  The series includes the KH-10 Dorian Manned Orbiting Laboratory concept.

**Build Notes**
- Agena forms part of the satellite so there is no decoupler above the Telemetry Response Unit, with the exception of KH-7, which detaches from the Agena-D and has its own Orbital Control Vehicle.
- KH-4B and KH-8 have a second SRV housed in the dual return capsule adapter.
- The SRV is built as a stack from the top down.  It is recommended to put the Capsule pod's "Collect All" action in an Action Group.

![Spyglass](https://user-images.githubusercontent.com/12999059/88410362-325af400-cdce-11ea-9d6a-ddfd4c8492a0.png)

**Comment by friznit** [comment]
### Ranger Programme
The Ranger (BDB Burke) series of probes were designed to take close up images of the lunar surface before impacting on the moon.  Block 1 flights were engineering tests for the Atlas-Agena launch vehicle and were instrumented for high earth orbit science, and so were not equipped with a mid course correction engine.  Block 2 sported a seismometer housed in a separate capsule that was slowed by a rocket motor to survive impact on the surface while Block 3 had a high resolution film camera.  The Ranger design was used as the basis for Mariner 1 & 2 Venus flyby probes.

**Build Notes**
- Some of the experiments need multiple parts to work, such as the Burke-EDA1 and EDA2.
- The fuel and thrust of the Staara-10 SRM on Block 2 should be adjusted to suit the gravity of the target body for a soft landing.  It is recommended to put the SRM Shut Down action in an Action Group.

![Ranger Series](https://user-images.githubusercontent.com/12999059/85877793-9ab6b580-b7cf-11ea-96d9-900c5aa15de5.png)

**Comment by friznit** [comment]
### Nimbus Programme
Nimbus (BDB Aeolus) were a series of second-generation meteorological research and development satellites launched into near-polar sun-synchronous orbits.  Nimbus 3 was the first satellite to use a SNAP-19 RTG to augment the solar arrays.

![Nimbus](https://user-images.githubusercontent.com/12999059/74587671-a73f2c00-4fed-11ea-9c16-22bdfeb476b7.png)

**Comment by friznit** [comment]
![front_Lunar Orbiter_3](https://user-images.githubusercontent.com/12999059/74572920-c9966280-4f77-11ea-9816-757a9d965901.png)

**Comment by CobaltWolf** [comment]
that's definitely not an Atlas Agena friz :P

**Comment by friznit** [comment]
### Science & Exploration Satellites
The Vanguard program was intended to launch the first artificial satellite into orbit, though it ultimately lost that race to Sputnik and ultimately Explorer-1 became the first US satellite to successfully reach orbit.  Meanwhile TIROS-1 was the first in a series of Television Infrared Observation Satellites that proved there was a practical scientific application for studying the Earth from space.  Since those early days there have been hundreds of science and exploration satellites launched.

![Sci ExplorationGrp](https://user-images.githubusercontent.com/12999059/75275901-1fcb9700-57fd-11ea-96f2-c0ec046f4ced.png)

![front_Lunar Orbiter_3](https://user-images.githubusercontent.com/12999059/74587976-96dc8080-4ff0-11ea-9b07-fd989dc8e404.png)

![OGO](https://user-images.githubusercontent.com/12999059/74611276-2027ac00-50f2-11ea-8e0a-f1c5a8d2405b.png)

**Comment by CobaltWolf** [comment]
that's not S-46 dad pls i told you not to share that

**Comment by friznit** [comment]
It's too late, it's out in the wild.  History has been rewritten forever.  The Blue Dog has spoken.  We must belieeeeeeeve.

**Comment by CobaltWolf** [comment]
ok but pls 

Also I need to check the length on the Thor tanks, it looks like the ELTT might be a bit short...

**Comment by friznit** [comment]
### Pioneer Programme
The Pioneer (BDB Pilgrim) programmes were two series of uncrewed space missions for lunar and planetary exploration.  Five years after the Able space probe missions ended, NASA reused the name for a series of satellites to measure interplanetary weather (Pioneer 6-9) and conduct flyby missions of Jupiter, Venus and Saturn.  Pioneer 8 & 9 (same build as Pioneer 6) were accompanied by a small Test & Training Satellite that was nestled inside the engine fairing of the Delta E upper stage.

![Pioneer Prog](https://user-images.githubusercontent.com/12999059/96104746-1b113b80-0ed1-11eb-817c-d3c79868e5ef.png)

**Comment by CobaltWolf** [comment]
Just ignore 5, the parts to make it are getting removed and there's enough other early payloads with dedicated parts.

**Comment by friznit** [comment]
### Explorers Programme
Explorer 1 (BDB Pathfinder) was the first US spacecraft to achieve orbit.  Since then, over 90 Explorer space missions have been launched with more planned in the future.  Satellites that failed to reach orbit did not get an Explorer number designation (such S45 and S46).

![Explorer Prog](https://user-images.githubusercontent.com/12999059/74971332-d7386600-5417-11ea-9b5e-7d042081159b.png)

**Comment by CobaltWolf** [comment]
:thonk:
Double cone?

The only Juno 1 payload in BDB is Explorer 1. Idk what the "big ball" is

Explorer 1, 7, 8, S45 (never reached orbit), S46 (never reached orbit) and 11 are all buildable. 

I don't want Explorer 6 in the same way I don't want Pioneer 5.

IMP (Explorer 18) is buildable as well as AIMP (Explorer 33). I might need to send you crafts for those since the different B9 switches and stuff should be set up specifically for them.

**Comment by friznit** [comment]
### Early Communications Satellites
Courier (BDB Messenger) was the world's first active repeater communications satellite.  Telstar (BDB Kompfner) allowed the first live TV broadcasts between the US and Europe whilst Relay 1 (BDB Repeater), launched later the same year, broadcast live images between US and Japan.  They can all operate as simple low power relay satellites for the early career game.  The Interim Defense Communication Satellite Program (IDCSP), available slightly later, has a unique payload mechanism allowing an entire constellation of small relay satellites to be deployed in one launch.

![CommSats](https://user-images.githubusercontent.com/12999059/74972007-e4a22000-5418-11ea-8aaa-db6dcc2b8498.png)

![IDCSP](https://user-images.githubusercontent.com/12999059/69492157-78a23100-0e96-11ea-88ca-17bbd1b3eb45.png)

**Comment by CobaltWolf** [comment]
Telstar 1 was a Thor-Delta (so, shorter upper stage tank and uses the longer tapered 1.25m>0.9375m adapter)

**Comment by friznit** [comment]
Right.  Telstar 2 was Delta B.

**Comment by friznit** [comment]
### Orbiting Astronomical Observatory
The Orbiting Astronomical Observatories (BDB Roman) provided the first high quality observations of space objects in ultraviolet light.  OAO-1 was uniquely launched on Atlas-SLV3B.  The Atlas SLV OAO-3 Copernicus telescope remained operational for nearly 10 years and its success led to the instigation of the Hubble space telescope.

![BDB OAOw](https://user-images.githubusercontent.com/12999059/95790409-357fc500-0cd7-11eb-9b05-a0485f13ff77.png)

**Comment by Morphisor244** [comment]
I think it's worth mentioning that in the Ranger block 2 build, it shows the EDA 1 and 2 parts - but the actual experiment is on the EIA analyzer part, which requires the other 2 before it can function. That part is not in the build guide however. I couldn't quite figure out if it's right that way.

**Comment by friznit** [comment]
> I think it's worth mentioning that in the Ranger block 2 build, it shows the EDA 1 and 2 parts - but the actual experiment is on the EIA analyzer part, which requires the other 2 before it can function. That part is not in the build guide however. I couldn't quite figure out if it's right that way.

I suspect the they were added as greebles by Cobalt when he did the craft file and I dutifully recorded them.  According to Gunter's, [Ranger Block 2 ](https://space.skyrocket.de/doc_sdat/ranger_bl2.htm) included the TV camera, gamma ray spectrometer on the boom, radar altimeter and the rough lander ball thing.  I'll removed the EADs from the build guide.

**Comment by OrbitalManeuvers** [comment]
Hello! Couple questions about science and Nimbus 1...

- are those dual radiometers on the underside? is there any benefit to having multiple? it's a re-runnable type.
- are there more experiments on top of the torus?

I found the following text on https://earthobservatory.nasa.gov/images/84542/the-legacy-of-nimbus

"Launched on August 28, 1964, Nimbus 1 sent back more than 27,000 images before its solar-power systems failed on September 22, 1964. It was the first NASA satellite to provide both daytime and nighttime images of hurricanes."

It would be neat if our Nimbus 1 could do some sort of photographic science, since that was a huge milestone of the mission. Currently there isn't a lot unlocked when Nimbus/Delta become buildable with the stock tech tree. I think just the Zafar, SG-1/4 ... none of which can "send back" multiple images.

**Comment by friznit** [comment]
> Hello! Couple questions about science and Nimbus 1...
> 
> * are those dual radiometers on the underside? is there any benefit to having multiple? it's a re-runnable type.
> * are there more experiments on top of the torus?
> 
> I found the following text on https://earthobservatory.nasa.gov/images/84542/the-legacy-of-nimbus
> 
> "Launched on August 28, 1964, Nimbus 1 sent back more than 27,000 images before its solar-power systems failed on September 22, 1964. It was the first NASA satellite to provide both daytime and nighttime images of hurricanes."
> 
> It would be neat if our Nimbus 1 could do some sort of photographic science, since that was a huge milestone of the mission. Currently there isn't a lot unlocked when Nimbus/Delta become buildable with the stock tech tree. I think just the Zafar, SG-1/4 ... none of which can "send back" multiple images.

They're just made to look like the historical craft.  In Kerbal terms the multiple radiometers are redundant.  The rest of your question would be better to ask on the BDB Dev Github!

**Comment by zorg2044** [comment]
@friznit the in game BDB name for the OAO series is "Roman" fyi.
