### ISSUE TITLE
Juno II & IV Update

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#45]
- [x] Juno II
- [x] Juno IV

**Comment by friznit** [comment]
![image](https://user-images.githubusercontent.com/12999059/96154441-b7096a00-0f06-11eb-8434-0556e36894ce.png)

**Fourth Stage**
- "Vicenza" SRM cluster & payload
**Third Stage**
- BD-SPD-05 Decoupler
- Chryslus-IVA-160 Liquid Fuel Tank
- Chryslus-IV-K6 "Seeker" Liquid Engine
- Chryslus-IVB-SIA 1.25m Structural Interstage (Short part switch)
**Second Stage**
- Chryslus-IVB-440 Liquid Fuel Tank
- Chryslus-IVB-EMS 1.25m Engine Mount
- Chryslus-IV-K45 "Hunter" Liquid Engine
- Chryslus-IVB-SIA 1.25m Structural Interstage (Long part switch)
**First Stage**
- Chryslus-IIAGC Guidance Unit
- Chryslus-2000 Liquid Fuel Tank
- Chryslus-EF Engine Fairing
- RL79 Liquid Engine (Chryslus-3DS "Polaris" & Jupiter Exhaust part switch)
- Chryslus-EE5 "Rhesus" Vernier Exhaust Engine (placed on engine fairing and lined up with the exhaust on the Polaris)
**Boosters**
- Dioscuri-ESMR Radial Decoupler (in 4x Symmetry)
- Dioscuri Solid Rocket Booster (Dioscuri-1 part switch)

![Juno IVB](https://user-images.githubusercontent.com/12999059/72464236-c79c8080-37cc-11ea-9d52-11ff0f5c5f33.png)

Juno IVB uses LR79 NA13 engine.

The Jupiter first stage tank and 6K third stage tank are under-fueled by default.  Propellant loading should be adjusted depend on the mission profile with reduced upper stage loading offset by increased first stage propellant and vice-versa.

**Comment by zorg2044** [comment]
Reference on propellant loading:
http://www.spacelaunchreport.com/jupiter7.html

" Propellant loading would vary depending on the mission type, with maximum upper stage loading for LEO missions and reduced loading for lunar or escape missions.  Reduced upper stage propellant loads would be offset by increased first stage propellant loads, and vice-versa."
