### ISSUE TITLE
PMA-1 and PMA-2 in your ISS page are in the wrong way

### ISSUE THREAD

**Issue by cjournois** [friznit/Unofficial-BDB-Wiki#46]
The two parts need to be in the opposit way.
![ISS (7)](https://user-images.githubusercontent.com/44445341/74089777-fa245b00-4aa4-11ea-8f9f-17680563e663.jpg)

**Comment by friznit** [comment]
So they are.  Not sure how I missed that.  I might fix it one day! :)

Also check P3-P1 / S3-S1 Truss setup - should be using offset node.
