### ISSUE TITLE
OmegA SDLV Description

### ISSUE THREAD

**Issue by ionenjoyer** [friznit/Unofficial-BDB-Wiki#49]
The OmegA description is mildly inaccurate, with mistakes such as saying the Castor 1200/600/300 is a STS SRB. While sharing features such as diameter, the Castors use HTPB and have a carbon composite case, while STS SRBs used PBAN-APCP, and steel cases.
I have written a rough draft below, with corrections and additions of what I would consider to be 
useful additional information. Apologies if this appears brash, or condescending.

OmegA, also known as OmegAAAAAAAAA, is the Northrop Grumman Innovation Systems (NGIS) plan for a next gen launcher using the new Castors 1200/600/300 and a cryogenic upper stage powered by dual RL10-C-5-1, with a layout similar to the DCSS. The design principle is the same as Ares 1 and the Liberty rocket, which would have used the Ariane 5 second stage. The Castor 1200 has been proposed as a replacement for the SLS 5 segment SRBs, as part of the [BOLE](https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20190002126.pdf) program.

**Comment by friznit** [comment]
Many thanks - updated!
