### ISSUE TITLE
Not specifying

### ISSUE THREAD

**Issue by KazBodnar** [friznit/Unofficial-BDB-Wiki#50]
On the Saturn MLV page, you say,

> Second Stages
> MS-II (same size as S-II; 5x J-2 Engines)
> MS-II-1 (0.625m stretch; 5x J-2 or J-2T Engines)
> MS-II-1A (MSIIA Liquid fuel tank; 7x J-2 Engines)
>MS-II-2 (MSIIA Liquid fuel tank; 5x HG-3 Engines)
> First Stages
> S-IC-1 (MS1C-25 Liquid fuel tank; 5x F-1A Engines)
> MS-IC-1A (MS1C-25 Liquid fuel tank; 6x F-1 Engines)
> MS-IC-4(S)B (5m stretch; 5x F1 Engines)

You son't specify how to build these. This is in most of the pages, and I can't build almost any of the rockets.

**Comment by friznit** [comment]
It's right there in the brackets - e.g. MS-II is the same as the S-II stage; MS-II-1A uses the MSIIA liquid fuel tank.  Be sure to read the notes above where it states "Various post-Apollo optimised and stretched tankage is available in the BDB Extras folder."
