### ISSUE TITLE
Mercury & Gemini Update

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#51]
- [x] Mercury
- [x] Mercury Lab
- [x] Gemini
- [x] Gemini B (refer to MOL build on Satellites page)
- [x] Big Gemini 1967 (Conical SM to match S-IVB diameter)
- [x] Big Gemini 1969 (Cylindrical design)
- [x] Lunar Flyby Gemini
- [x] MORL Ferry Gemini
- [x] Augustus ORV
- [x] Ahistorical stuff reference in text only (Rumble Seat; Shuguang; Arrow)

![front_Mercury_2](https://user-images.githubusercontent.com/12999059/78798493-f92e7d80-79b0-11ea-8b88-0b6ba7e1fe27.png)

![front_Mercury Lab_1](https://user-images.githubusercontent.com/12999059/88412624-c9757b00-cdd1-11ea-9913-23609485885f.png)
_One man Mercury lab concept intended to be launched on an Atlas-Agena LV-3A_

**Comment by friznit** [comment]
![front_Gemini_1](https://user-images.githubusercontent.com/12999059/88594821-d73d3180-d059-11ea-94dc-211d5a514afe.png)

**Comment by friznit** [comment]
![Titan II GLV Build Guide](https://user-images.githubusercontent.com/12999059/88388695-f06d8600-cdac-11ea-99ff-ab63df6a837b.png)

**Comment by friznit** [comment]
![Augustus AORV](https://user-images.githubusercontent.com/12999059/88413562-50772300-cdd3-11ea-890f-a46382395948.png)

_Augustus RRV_

**Comment by OrbitalManeuvers** [comment]
For the Hermes OMS, are you just offsetting the decoupler between the heatshield and the OMS? Or is there a part I've missed that makes the decoupler sit closer to the heatshield?

Edit: oh sorry, I think I'm seeing it now ... you have the retro pack and the interstage on there ... right?

**Comment by friznit** [comment]
> For the Hermes OMS, are you just offsetting the decoupler between the heatshield and the OMS? Or is there a part I've missed that makes the decoupler sit closer to the heatshield?
> 
> Edit: oh sorry, I think I'm seeing it now ... you have the retro pack and the interstage on there ... right?

Right.  The retropack has a secondary node for attaching the decoupler so it sits snuggly under the heatshield.  You could dispense with the decoupler if you want, since the BDB interstage has a decoupler built in.

**Comment by OrbitalManeuvers** [comment]
Noticing that several Gemini-era parts have changed names from the image above. This might be more of a general question but ... can we help? Do you want detailed reports about where a part is shown and what its new name is? Idk if you're concerned about the exact names since usually the parts are pretty findable anyway, so thought I'd ask before posting that kind of detail.

**Comment by friznit** [comment]
> Noticing that several Gemini-era parts have changed names from the image above. This might be more of a general question but ... can we help? Do you want detailed reports about where a part is shown and what its new name is? Idk if you're concerned about the exact names since usually the parts are pretty findable anyway, so thought I'd ask before posting that kind of detail.

Thanks - it's enough to point out that they've changed and I've been terribly lazy copying the old text!  You don't need to list all the new names, I can look them up!

**Comment by friznit** [comment]
> Noticing that several Gemini-era parts have changed names from the image above. This might be more of a general question but ... can we help? Do you want detailed reports about where a part is shown and what its new name is? Idk if you're concerned about the exact names since usually the parts are pretty findable anyway, so thought I'd ask before posting that kind of detail.

Just checked - they all seem correct.  I've not includes the full fictional designation in the titles

**Comment by friznit** [comment]
> Noticing that several Gemini-era parts have changed names from the image above. This might be more of a general question but ... can we help? Do you want detailed reports about where a part is shown and what its new name is? Idk if you're concerned about the exact names since usually the parts are pretty findable anyway, so thought I'd ask before posting that kind of detail.

I just checked all the part names and they seem correct (less the fictional part designations which I've skipped)

**Comment by OrbitalManeuvers** [comment]
A few nitpicks:
Hermes Recovery Module
Prometheus:  "Spacecraft Stack Decoupler" and "Lelantos liquid engine" - neither one has a "II" designation
Vented Stack Decoupler

Sorry :)

**Comment by OrbitalManeuvers** [comment]
Also one last detail on this page ... just to make sure it's on purpose. Your Gus thrusters are shown rotated 90 degrees from what I'm getting. Like your builds, with camera looking at the windows, attach nodes are not left and right of center as shown, but near and far from your camera. Then I was thinking maybe you did that on purpose to show them better so if that's the case please ignore all of the above rambling.
