### ISSUE TITLE
Update Image Collage

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#53]
- [x] Vanguard, Redstone, Juno I, Juno II, Juno IV
- [x] Thor-Delta Evolution - Thor Able to Delta J
- [x] Delta Evolution -  LTT, ELTT, Delta II, Delta III
- [x] Delta IV
- [x] Mercury, Gemini, GATV
- [x] Satellites
- [x] Upper Stages: Agena, Agena-SOT, Delta K, HOSS, Centaur D, Vega

**Comment by friznit** [comment]
![Jupiter-Juno Line Up](https://user-images.githubusercontent.com/12999059/93396118-08bec600-f86f-11ea-91a9-08a5b14bf9a1.png)

![Thor Delta Evolution](https://user-images.githubusercontent.com/12999059/93369975-0b59f500-f848-11ea-93d8-2b0d42e5a8fe.png)

![Delta LTT Line Up](https://user-images.githubusercontent.com/12999059/93379439-bf15b180-f855-11ea-8bda-4e837cae9d5a.png)

![Delta ELTT Line Up](https://user-images.githubusercontent.com/12999059/93593901-ce5b4300-f9ac-11ea-90de-a613e2c7925f.png)

![Delta IV Lineup](https://user-images.githubusercontent.com/12999059/93593077-4a548b80-f9ab-11ea-928d-2ab288b76bc6.png)

![BDB Sats Line Up](https://user-images.githubusercontent.com/12999059/93593933-dca95f00-f9ac-11ea-8d8e-2b318ec489b1.png)

**Comment by friznit** [comment]
![Mercury Gemini](https://user-images.githubusercontent.com/12999059/93396845-42dc9780-f870-11ea-95e9-cc2f2c648a52.png)

**Comment by friznit** [comment]
![BDB Sats Line Up](https://user-images.githubusercontent.com/12999059/93398063-bbdcee80-f872-11ea-962e-cbf2ea777f56.png)

**Comment by OrbitalManeuvers** [comment]
On the JupiterC, is the open nosecone variant supposed to used?

**Comment by onyxx72** [comment]
> On the JupiterC, is the open nosecone variant supposed to used?

If you want.

**Comment by OrbitalManeuvers** [comment]
yup yup finally found some better images with the curved nosecone underneath the washing machine.
