### ISSUE TITLE
Vanguard

### ISSUE THREAD

**Issue by jamesbreith** [friznit/Unofficial-BDB-Wiki#54]
Hey there, what happened to the one of the parts. Also some of the parts are missing too. Can u update the wiki plz

**Comment by friznit** [comment]
I need more details please!  What's missing?

For info, an update to BDB is just around the corner - the new Vanguard is documented here https://github.com/friznit/Unofficial-BDB-Wiki/issues/23#issuecomment-552204845

**Comment by jamesbreith** [comment]
It looks like the Staara-20 is gone but maybe I haven’t supposed to install correctly. I downloaded it from CKAN though

**Comment by friznit** [comment]
Staara-20-IIA "Aquilae" Solid Rocket Motor is still there in the first tech node.  The CKAN install should be fine  - try reinstalling?
