### ISSUE TITLE
1.7 To Do

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#55]
- [x] Strawman
- [ ] Oscar 1 (piggy backs on Agena B)
- [ ] Transit 2A and GRAB
- [ ] SAF Updates (Vanguard in particular)
- [ ] Revamp Atlas pages including build guides, clarifications, auto jettison feature
- [x] Check Agena tank names
- [x] Upper Stages: DCSS/ICPS

**Comment by friznit** [comment]
The Strawman series of SIGINT satellites, known for decades only as "Heavy Ferrets", are Agena-D based ELINT satellites launched on Thorad-SLV2G.

Place two solar panels at an angle flush with the Agena equipment truss with both panels set to 25 degrees in the variant part switch.  The third panel is placed flat on the opposite side of the truss with an angle of 35 degrees set in the variant part switch. 
 Note that only Strawman 4 has the additional "Harvester" dish antenna.

![Strawman](https://user-images.githubusercontent.com/12999059/101918225-0398bb00-3bc1-11eb-9a3e-69ef24c30ea7.png)

**Comment by onyxx72** [comment]
> The Strawman series of SIGINT satellites, known for decades only as "Heavy Ferrets", are Agena-D based ELINT satellites launched on Thorad-SLV2G.
> 
> ![front_Untitled Space Craft_5](https://user-images.githubusercontent.com/12999059/101910724-42c20e80-3bb7-11eb-83a2-8fb9a1159fe3.png)

Does Strawman has a 3 solar panel configuration?

**Comment by friznit** [comment]
Update the pic with correct colour scheme and fixe the read panel.  Yes - it only has 3 solar panels.

**Comment by onyxx72** [comment]
> Update the pic with correct colour scheme and fixe the read panel. Yes - it only has 3 solar panels.

Ok. Thanks.

**Comment by Pappystein** [comment]
Suggestion for Atlas as part of 1.7 update.    Include mention of the Auto Separation that JSO has introduced into the Atlas Booster Skirt.   Using the same steps to figure out what time to jetteson the booster skirt, instead pay attention to the G-Forces/TWR and then set the auto jettison to that Gforce or slightly higher.  Booster skirt has to have Auto seperation manually activated in VAB.
