### ISSUE TITLE
Titan III family,   series of minor issues

### ISSUE THREAD

**Issue by Pappystein** [friznit/Unofficial-BDB-Wiki#57]
Most of these issues are about when the AJ9 vs. AJ11 was used.   

If the Rocket stage has a Roman Numeral IIIx, then it flys on AJ-9s. If the Rocket is a 2x, or 3x model, then it flys on AJ-11s.   The exception is the in-appropriately redesignated  Titan 23G, which flew on AJ-5s.

Titan IIIA only ever flew with AJ5 engines. It is the only Titan III not to fly with uprated engines.

Only the Original Titan IIIB (missing from your Titan IIIB table) flew with the AJ9 engines.  2nd stage would be an AJ-5 engine, not the LR91-AJ-11.     

Titan IIIM, as depicted in your document, is correct for the proposed launcher...  However, you designate it as the prototype flight, which was Titan III-M, and it flew with a Titan IIIC stack with the first all-up flight rated AJ-11 set of engines and UA1205 man-rated SRMs.  

Titan IIIC is perfect except AJ-11 for the upper stage (should be AJ-5(9))
Titan 23C is perfect.

Titan IIID is ACTUALLY the Titan 23D.   Titan IIID did, in fact, only fly on AJ-11 engines and thus has a 23 designation.

Titan 34D did not have a stretched upper stage (mentioned in the text but not the table). It only had the IIIM tanks and the UA-1206 as different from the Titan 23D.

Lastly, Comercial Titan (CT3) and Titan IV both flew on AJ-11A engines, which are not currently in BDB.    I do not know if this should be mentioned in the Wiki.   I will see about getting the AJ-11A added to the game as it is actually a significant upgrade for both main and 2nd stage engines.  The AJ-11A finally had the man rating items stripped from it, lightening it by almost 200kg for the LR87 and 50kg for the LR91... both had between a 5-7% thrust increase with a slight change to ISP over the man-rated AJ-11.

Suggested Text change on Titan MOL/3M:

The Titan IIIM was to launch the Manned Orbital Laboratory.  As part of the test of new hardware for this program, a prototype was launched based on the Titan 23C called III-M.   The III-M Utilized the new LR87 and LR91 AJ-11 variants that had been tested one part at a time on earlier Titan III launches.   The UA-1205 for the III-M was man-rated and could be shut down in flight via a thrust canceling device in the nosecone.   These changes made the III-M a prototype of sorts for the uprated Titan 23C stack, which would start flying in the year after the III-M Test launch.     

The Actual MOL launch vehicle would have many changes over the III-M test flight.   The Designation would be Titan IIIM, and it would fly with the stretched First stage tankage, the UA-1207 man-rated SRM using the same features as the test UA-1205s launched on the previous III-M test ship.     Depending on the mission, it would fly with either the Transtage or no upper stage.   The IIIM never flew, and while we can infer the designation would be Titan 33M, we can not know for certain since it was never ordered into production.

**Comment by friznit** [comment]
Tweaked!

**Comment by Pappystein** [comment]
one more section needs a tweak.    Titan 23 and 24B


Titan 23B | Titan II tanks; LR-87-5 | LR-91-11 | Agena D | 0.9375m
-- | -- | -- | -- | --
Titan 33B | Titan II tanks; LR-87-5 | LR-91-11 | Agena D | 1.875m



Should be -11 for both stages

AND


Titan IIIA | Titan II tanks; LR-87-5 | LR-91-11 | Transtage
-- | -- | -- | --


Should be -5 for 2nd stage.   

THANKS FOR fixing these!
