### ISSUE TITLE
Is there something wrong with the Atlas Wiki Page?

### ISSUE THREAD

**Issue by Lodkins** [friznit/Unofficial-BDB-Wiki#58]
I went to the Atlas's Wiki Page and it's all Garbled, but it looks fine on phone, but it's all garbled on Windows Computer.

![image](https://user-images.githubusercontent.com/53875245/108063982-a3d7e980-7021-11eb-8280-80a24d2a2c9b.png)

**Comment by zorg2044** [comment]
looks ok to me but I noticed something similar on the Payload Performance page. Fixed by saving the page again without making any changes. Did the same for Atlas even though it looked ok to me. Please try again.

**Comment by friznit** [comment]
I think it's a wider github issue.  Some of my other wiki pages were doing the same thing but seem to have corrected themselves after a couple of days
