### ISSUE TITLE
Saturn Update To Do

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#60]
PSketch 1/2

Build guides for:

- [x] [Saturn Concept Development](http://www.astronautix.com/graphics/s/satc12c5.gif) (A1 to C5)
- [x] Saturn C-2 Guide
- [x] Saturn I
- [x] Saturn IB MLV (1967 AAP study for Earth Orbital Missions)
- [x] Saturn IB SRM (1966 Study UA - INT-05 to INT-27)
- [x] Saturn V (Apollo)
- [x] Apollo 11 CM
- [x] Apollo 17 CM
- [x] Apollo 11 Walkthrough
- [x] ASTP
- [x] Saturn Intermediate Payload (1966 Intermediate Payload Study INT-17/18/19/20)
- [x] Saturn V MLV (1965-1968 AAP Studies & NASA ELV)
- [x] Saturn V Derivatives (S-ID)
- [x] Upper Stages - S-IV, S-IVB, ETS S-IVC, S-II
- [x] ETS Saturn IC & MB
- [x] ETS Apollo
- [x] AARDV
- [x] ETS AARDV Block II
- [x] Skylab
- [x] ETS Spacelab
- [ ] [ETS Pegasus Upper Stage](https://forum.kerbalspaceprogram.com/index.php?/topic/122020-112x-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v190-%D0%BF%D1%80%D0%BE%D0%B1%D0%B5-13dec2021/&do=findComment&comment=4106564)
- [x] Venus Flyby
- [x] Pegasus
- [x] Big G Update
- [ ] Tianjia Station (Dawn of the Dragon Alt History)
- [x] [Agena Horizon Scanner](https://forum.kerbalspaceprogram.com/index.php?/topic/122020-112x-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v190-%D0%BF%D1%80%D0%BE%D0%B1%D0%B5-13dec2021/page/979/#comment-4097533)
- [x] Add nuclear exp package to GATV/ATDA image

**Comment by TCORPStudios** [comment]
Would it be a good idea to work on the Atlas parts last, and work on the Saturn and Apollo parts first?

**Comment by friznit** [comment]
![Saturn V Page Divider 2](https://user-images.githubusercontent.com/12999059/136666323-014f1e08-0261-4556-a94e-36b3c1ed988f.png)

![Apollo 11 CSM](https://user-images.githubusercontent.com/12999059/136782138-6978bff8-6fc6-4143-a0f3-651770850b1b.png)

![Apollo 11 MLEM](https://user-images.githubusercontent.com/12999059/136782150-dbb942f7-e7e7-4e9f-93fd-8452ce696881.png)

![Apollo 17 CSM](https://user-images.githubusercontent.com/12999059/136782176-9c2e52f3-cadb-4c3d-92a6-a227f47e06e9.png)

![Saturn V Build](https://user-images.githubusercontent.com/12999059/138138153-1b39148c-bd75-4dbf-8193-fdb67a6e87e0.png)

![Saturn V Staging](https://user-images.githubusercontent.com/12999059/140779974-0651d87a-dabc-4311-8d82-2e26a41a3f8f.png)

![Apollo TD E](https://user-images.githubusercontent.com/12999059/136784694-3bc49cce-28fe-48dc-b70a-8399f4234c05.png)

![Saturn V Page Divider PS](https://user-images.githubusercontent.com/12999059/136784767-96473efa-4d1a-402d-a316-82db061b69ed.png)

Saturn V is a little overpowered even on scaled up systems such as JNSQ or KSRSS 2.5x.  For a more realistic flight profile the S-IC stage should be set to 80% fuel then adjusted for extra payload mass such as Life Support mods.

**Comment by friznit** [comment]
![Saturn I Guide](https://user-images.githubusercontent.com/12999059/147228177-02562853-8fa1-48b1-97eb-9ffc997e4cf4.png)

![Saturn I Blk 2 AS101 (BP13)   Saturn IB](https://user-images.githubusercontent.com/12999059/152380239-5614d754-8841-48e6-bf97-c2c1769fa615.png)

**Comment by friznit** [comment]
![Skylab Top](https://user-images.githubusercontent.com/12999059/137488895-18010a47-5b08-4227-8e5b-bc5ff60e88df.png)

Skylab is a large orbital lab supporting up to 6 scientists. Two wet lab variants and parts to build Spacelab (from the Eyes Turned Skyward alternate history timeline, not to be confused with the the Space Shuttle Spacelab), and the Venus Flyby craft are available.

Tags: Hokulani

## Basic Build Guide
Start by placing a Sarnus-S-IVB-IU Instrument Unit as the root part, then add the Hokulani-OWS Orbital Workshop and RMPS Radiator Unit below.  Stack the ALM Airlock and MDA Multiple Docking Adapter above the IU.  The RT90 Truss Structure attaches to a hidden node in the Airlock Module so that it sits over the top of Docking Adapter assembly.  Finally, assemble the Telescope on the truss and add the external experiments, antennae, solar panels and RCS units.  Make sure that the OWS Orbital workshop is not the root part.  It causes a bug with the shield jettison.

![Skylab Offset](https://user-images.githubusercontent.com/12999059/137493788-8206f07d-e968-4d5d-b03e-20226ff59c56.png)

From Top to Bottom:

- Kane-OCO Telescope Mount Experiments
  - Hokulani EVE Lightbulb (placed on the block at the top of the ladder)
  - 4x Kane-OCO-PP Solar Panel (1x FMU config, 1x Triangle config)
- Kane-OCO Telescope Mount (Ladder config on)
  - Kane-OCO-CA Command Antenna
- Hokulani RT90 Truss Structure (attaches to hidden node in Airlock Module)
- Hokulani-MDA Multiple Docking Adapter
  - 2x Kane-11-DDM6 Passive Docking Mechanism
  - Hokulani Experiments (see diagram)
- Hokulani-ALM Airlock Module
  - 2x Hokulani-DCA Discone Antenna (rotated to extend at 45 degrees)
- Sarnus-SIVB-IU Instrument Unit (must be the root part)
- Hokulani-OWS Orbital Workshop
  - 2x Hokulani-PPA Solar Panel (these are installed off centre and the panel on the right sits just behind the longer raceway)
- Hokulani-RMPS Radiator Unit
  - 2x Hokulani-ACT RCS Units (placed top and bottom on the flat part of the radiator)

![Skylab Side Labelled](https://user-images.githubusercontent.com/12999059/137493732-d7059e86-d598-4d77-b2c2-796214cc5fdf.png)

Skylab is surrounded by a sun shield with the white part of the Workshop facing 'up' towards the sun.  Historically, the shield was accidentally torn off during ascent leaving a small panel of shielding underneath a single surviving solar panel.  A parasol sunshield (Hokulani-UB22 "Brolly") was installed on EVA to provide emergency cooling.  There is a B9 Switch to recreate the historical look:

1) Launch as planned - Shield On (Auto Jettison Off); Panel On
2) Launch as it happened - Shield On (Auto Jettison to simulate the accident); Panel On
3) Ahistorical, all gold Skylab - Shield Off; Panel Off (Texture Unlimited mod required for extra shiny gold)

Skylab is launched on a two stage Saturn V rocket: the lower S-IC first stage and S-II second stage. Skylab itself replaces the S-IVB upper stage and Apollo crew module. Once in orbit, the Truss Structure is rotated to place the Telescope Mount in position (requires Breaking Ground DLC).

![Skylab Launch Config](https://user-images.githubusercontent.com/12999059/137493869-bf4cc1f2-94ea-40c5-aa44-6fc2975fe0e5.png)

## Wetlab Configuration
The original plan was to launch Skylab on a Saturn 1B rocket as a wetlab. Once in orbit, the modified S-IVB stage would be drained of fuel and converted into a lab. The ATM would be attached to a LEM Ascent Module and launched with the crew separately. This assembly replaces the S-IVB stage.

- Replace OWS Orbital Workshop with a WWS Wet Workshop.
- Replace RMPS Radiator Unit with an S-IVB Engine Mount and J2 Engine
- Remove the Truss Structure
- Replace the upper docking port with an Apollo Active Docking Port

## ETS Spacelab
Additional parts are provided to build the Spacelab concept from the Eyes Turned Skyward alternate history timeline.

- Hokulani-RAM Adapter Module replaces the Airlock Module
- Hokulani-PPAx Double Solar Panel replace the regular short panels
- Hokulani-FRM Foreign Research Module - Flown up separately and docked to the end of the MDA
- Hokulani-EALM Expansion Airlock Module - Also flown up separately and docked to the upper docking node.  Final assembly requires some EVA to attach 4 EAS Struts.

![Spacelab Assembled PS](https://user-images.githubusercontent.com/12999059/137494766-dd0f6c40-5e06-44f0-8f5b-a4325128ad79.png)

**Comment by friznit** [comment]
![Saturn II INT-18](https://user-images.githubusercontent.com/12999059/137735589-0de3088a-5e86-499a-8ab9-21f9e10501dd.png)

_Saturn II INT-19_

**Comment by friznit** [comment]
**Saturn MLV**
Successive Saturn Modified Launch Vehicle studies as part of the Apollo Applications Program proposed a dazzling array of Saturn V derived concepts, intended to deliver uprated heavy launch vehicles based on existing hardware.

Constrained mainly by the height of the VAB and launch infrastructure, Saturn MLV features upgraded F1A engines, stretched fuel tanks and improved upper stage engines such as the J-2T or a hypothetical "Advanced Engine" (this guide uses the RL20-P3). Meanwhile, Saturn ELV is the result of a NASA in-house study given no height restrictions.

Other designs including the Saturn V/4-260, which works around load bearing challenges by adding liquid fuel tanks on top of massive AJ-260X solid rocket boosters. An alternate approach employed by the Saturn V-23(L) uses strap on liquid rocket boosters with 2x F1A engines each.

**Build Guide Notes**
The naming conventions from the various MLV studies can be confusing so they have been slightly simplified for the purpose of this guide.

The source docs refer to "Advanced Upper Stage Engines", often considered to be a reference to the conceptual HG-3, which was never developed.  The RL20-P3 is used as a drop in replacement here.

The fins on the S-IC stage provided aerodynamic stability in the event of a main engine failure to support a successful abort with the Launch Escape System.  Although many of the source doc images shows fins, it is likely that they would have been omitted from all post-Apollo Saturn builds to save weight.

The proposed length of fuel tanks varied a fair amount as studies matured over the years.  The tank extensions have been rationalised and rounded to the nearest available size in BDB.

BDB S-IV Extensions = 1.3/3/4.5/6
BDB S-II Extensions = 1.5/3/9
BDB S-IC Extensions = 3/6/9

Baseline Stage | B9 Tank Extension | Engine Number & Type
---|---|---
S-V        |  Centaur D   | 2x RL-10
S-IVB     |                     | 1x J2
MS-IVB  | 3m               | 1x J2
S-II         |                     | 5x J2
MS-II-1  | 1.5m             | 5x J2
MS-II-2  | 3m                | 5x J2
S-IC       |                      | 5x F1
MS-IC-1| 3m                | 5x F1A
MS-IC-4| 6m                | 5x F1
MS-IC-25| 9m              | 5x F1

![Saturn MLV-V-1 Baseline](https://user-images.githubusercontent.com/12999059/140526596-3472931e-8cd0-43c4-8482-f4daa088c03e.png)

Variant | First | Second | Third | Boosters | Comments
-- | -- | -- | -- | -- | --
MLV-V-1 | MS-IC-1 | MS-II-1; 5xJ2 or J-2T | S-IVB |   | J-2T allows short S-II interstage
MLV-V-1A | MS-IC-1; 6xF1 | MS-II-2;  7xJ2 | MS-IVB |   |  
MLV-V-2 | MS-IC-1 | MS-II-1 | MS-IVB; 1xRL-20 |   |  
MLV-V-3 | MS-IC-1 | MS-II-2 | MS-IVB; 1xRL-20 |   |  
MLV-V-3B | MS-IC-1 | MS-II-2; 4-7xRL20 | MS-IVB; 1xRL-20 or J-2T |   | Uprated S-IC with INT-17 on top
MLV-V-4(S) | S-IC | S-II | S-IVB | 4x UA-1205 |  
MLV-V-4(S)A | MS-IC-4 | MS-II-1 | MS-IVB | 4x UA-1205 |  
MLV-V-4(S)B | MS-IC-4 | S-II | S-IVB | 4x UA-1207 | V-22(S) with stretched tanks & adv engines dropped after Phase 1 study
MLV-V-23(L) | MS-IC-1; 5xF1 | S-II | MS-IVB | 25x4m (KSP Scale) LRB; 2x F1 | 24(L) with adv engines dropped after Phase 1 study
MLV-V-25(S) | MS-IC-25 | S-II | MS-IVB | 4x UA-1207 |
ELV | MS-IC-4 | MS-II-1; 7xJ2 | MS-IVB | 4x UA-1207 | NASA no size limit study
V/4-260 | S-IC | MS-II-2 |   | 4x AJ-260X with addt'l fuel tanks | Boeing study

![Saturn MLV](https://user-images.githubusercontent.com/12999059/142425393-a7ddd427-7649-44ee-a110-49b29854452e.png)

**Saturn Intermediate Payload**
Saturn intermediate payload concepts are intended to create lower-cost launch vehicle based on Saturn V hardware to bridge the gap between Saturn IB and Saturn V MLV.  Proposals include using the S-II as a first stage with modified sea-level J2 engines or standard J2's air lit after 'Stage 0' solid booster burn out.

Saturn V INT-20 uses the S-IC and S-IVB, skipping the S-II altogether and optionally reducing the number of first stage engines to compensate for the lower overall mass. INT-21 uses the S-IC and S-II second stage with no S-IVB upper stage. A similar design launched Skylab, given that the orbital workshop was a converted S-IVB stage.

Variant | First | Second | Third | Boosters | Comments
-- | -- | -- | -- | -- | --
INT-17 |   | MS-II-2; 4-7xRL20 | MS-IVB; 1xRL-20 or J-2T |   |  
INT-18 |   | S-II | S-IVB | UA-1205 or 1207 |  
INT-19 |   | S-II | S-IVB | Minute Man SRBs |  
INT-20 | S-IC; 3-5xF1 |   | S-IVB |   | 4x F1 Standard
INT-21 | S-IC | S-II |   |   |  

![Saturn INT](https://user-images.githubusercontent.com/12999059/151790930-51edc302-e7b4-4e9f-bcbe-1be7a8c28718.png)

_Saturn INT-17, INT-18, INT-20, INT-21_

**Saturn Derivatives**
Saturn V-A is identical to INT-20 but uses a 2-2 main engine shutdown sequence 61s apart.  Saturn V-B/C/D concepts are stage and a half designs, similar to Atlas. The first stage consists of five F1 engines, of which four are jettisoned leaving the single sustainer engine to carry the payload into orbit.  The engine fairing can be equipped with parachutes to enable the engines to be recovered.  S-IVB stage is added to the V-C for achieving higher orbits and an optional Centaur upper stage for deep space missions. The V-D is essentially a fully upgraded Saturn V with the addition of 4 massive SRBs. Truly a bonkers rocket.

Variant | First | Second | Third | Comments
-- | -- | -- | -- | --
A | S-IC |   | S-IVB | Same as INT-20
B | S-ID |   |   | S-IC tank
C | S-ID |   | S-IVB | Optional Centaur (S-V)
D (Uprated) | S-ID (+8m); 5x F1A | S-II; 5x J2S | S-IVB | 2/4x 120"; 156" or 260" SRB

![front_Saturn V-B Offset_1](https://user-images.githubusercontent.com/12999059/141980798-815e6df9-0f3f-4249-829f-9903d4f9c523.png)

**Comment by friznit** [comment]
Saturn Development | First | Second | Third | Fourth
-- | -- | -- | -- | --
Super-Jupiter | S-I 4xE1 (15x4) | Titan 1-1 (2xLR-87-3) | Titan 1-2 (LR-91-3) |  
Juno V-A | S-I 8xH1 | Jupiter Cluster 4xS-3 | Titan 1-1 | Titan 1-2
Juno V-B | S-I | Jupiter Cluster (11.5x3.3) | Titan 1-1 | Centaur C (2x RL-10A-1)
A-1 | S-I | Titan 1-1 | Centaur C |  
A-2 | S-IB 8x H1 (15x4) | Jupiter Cluster | Centaur C |  
B-1 | S-IB | Titan Cluster 4xLR-89-5 (10x4) | S-IV 6xRL-10 (8x3.75) | S-V (Centaur C) (1.875x5.6)
C-1 | S-I (Bl. 1) | S-IV | S-V |  
C-2 (1959) | S-I | S-III 4xJ2 (8x4) [SIVB Tank] | S-IV |  
C-2 (1961) | S-I | S-II 4xJ2 (14x4) [SIVB+6m] | S-IV | S-V
C-3 (1959) | S-IB-2 2xF1 (22x5) | S-II-C3 4xJ2 (8.75x5) | S-III | S-IV + S-V
C-3 (1961) | S-IB-2 | S-II-C3 4xJ2 (13.5x5) | S-IV | S-V
C-3B | S-IC-C3B 5xF1 (22x6) | S-II-C5B 5xJ2 (-2.5m) | S-IVB-C3B 1xJ2 (9.5x3.5) | S-V (Centaur E)
C-4 | S-IB-4 4xF1 (18x6) | S-II-4 4xJ2 (-5m) | S-IVB 1xJ2 (11x4) |  
C-4B | S-IC-C4B 5xF1 (21x6) | S-II-C5B | S-IVB-C5A (12x3.5) |  
C-5 | S-IC 5xF1 (26x6) | S-II 5xJ2 (15.5x6) | S-IVB |  


- Juno and A2/B1 need to kitbash Titan clustered tanks somehow
- C3 & C4 can kitbash using Restock of Near Future Launch Vehicles 5m fuel tanks
- C-8 wasn't even a concept - it was merely a mathematical study proving the impracticality of a Direct Ascent vehicle
- S-V (Centaur C / E = same thing just renamed by NASA) is not exactly a Centaur D but close enough to use here (with insulation on)

**Super Jupiter, A-1, C-1, C-2 & C-5 builds:**
- **Super Jupiter**: Prometheus I, Sarnus-SIVB-425 adapter, standard length S-I tank & S-I engine mount (Juno V config) with 4x E1 engines
- **A-1**: Inon D (insulation installed), Prometheus I first stage, Sarnus-SIVB-425 adapter, standard length S-I tank & S-I engine mount (Block 1 config) with 4x Sarnus-HD1-270 outer and 4x Sarnus-HC1-280 inner engines
- **C-1**: Same build as Sarnus I except engine fairing uses Block 1 config with no fins
- **C-2**: Use Inon D (insulation installed) as the S-V stage; S-IV stage same as Sarnus I; S-III uses standard length Sarnus-SIVB tank with (1959 variant) or 6m extension (1961 variant), SIVB Engine Mount (S-II Config) and 4x Sarnus HE2J "Dnoces" cryogenic engines; S-I stage same as Sarnus I

![Saturn Development](https://user-images.githubusercontent.com/12999059/141981806-94e837b6-8d3c-4344-bd75-9b3eed740404.png)

**Comment by friznit** [comment]
[ETS Saturn 1C & MB](https://www.alternatehistory.com/wiki/doku.php?id=timelines:eyes_turned_skyward_spacecraft_and_launch_vehicle_technical_data)

|ETS|First Stage|Boosters|Second Stage|Third Stage|
|---|---|---|---|---|
|Saturn IC     |Sarnus S-IE 1xF1-A    |                |S-IVB 1xJ2-S          | _Centaur E_ 2xRL10A-3 |
|Saturn M02 |Sarnus S-IF                |                 |S-IVB                     | _Centaur E_ |
|Saturn M43 |Sarnus S-IF                | 4x SRB1207 |S-IVC                 | _Centaur E_ |
|Saturn H03  |3x Sarnus S-IF           |                  |S-IVC                    | _Centaur E_ |

S-IF stage uses same S-IE tank with a 3.3m Extension.  S-IF was originally depicted with SOFI but was later retcon'd to the copper-coloured Anodized Aluminium like Atlas V.  Both colour options area available.
The single engine presumably needs some kind of roll control.  Showing 2x Bossart-IE "Finch" engines on engine mount here.
S-IVB is "the same as used on Saturn V but with J2-S," so assume 2x Ullage Motors as per late Saturn variants.
S-IVC has over 2x the prop mass of S-IVB so assume a 3m extension judging by the ETS illustrations.
Centaur E is similar to Centaur D but slightly heavier and with better fuel boiloff profile.  Use Centaur D with insulation on until start of Centaur burn.

![Saturn IC (ETS)](https://user-images.githubusercontent.com/12999059/149540384-c8569d92-1706-4310-9c2d-e3ec6aedafc6.png)

![Saturn ETS](https://user-images.githubusercontent.com/12999059/149540404-7a518fa4-7adc-442a-bbd6-ccd725dd2e63.png)

**Comment by friznit** [comment]
Kane Eleventy-One Munar Jaunt Mission Profile

![front_Saturn V 65x_1](https://user-images.githubusercontent.com/12999059/140773561-2ba06b48-3916-4311-9d2c-c2c8852fb7b1.png)

**Comment by friznit** [comment]
![front_Venus Flyby_3](https://user-images.githubusercontent.com/12999059/164062472-dcc4f706-4eb8-4e1d-95a3-7a86f39f64f1.png)

![front_Venus Flyby_2](https://user-images.githubusercontent.com/12999059/142035053-71d5e3df-fc3a-4933-b47a-abcd37bdde3d.png)

Note: SM is slightly shorter than Blk 2 and has a dual mount for 2x LMDEs

**Comment by friznit** [comment]
![S-IV](https://user-images.githubusercontent.com/12999059/142457619-72155c86-f8a8-4ed7-a5b3-05c7bea2ab10.png)

![S-IVB](https://user-images.githubusercontent.com/12999059/142429033-6f63043c-3c13-4bfc-89eb-9c8bbb6dc3e6.png)

**Comment by friznit** [comment]
**1966 S-IB SRM Studies (ULA)**

Variant |First | Second | Boosters |
-- | -- | -- | --
INT-05 | AJ-260-2 (1/2 Length) | S-IVB |  
INT-05A | AJ-260X (Full Length) | S-IVB |  
INT-11 | S-IB-11 (19m = 3.8m stretch) | S-IVB | 4x UA1207 (Stage 0)
INT-12 | S-IB-4; 4x H1 | S-IVB | 4x UA1205 (or 1207 with stretch S-IB)
INT-13 | S-IB | S-IVB | 2x UA1205 (or 1207 with stretch S-IB)
INT-14 | S-IB (+0 / 2 / 4m stretch) | S-IVB | 4x Minuteman-1
INT-15 | S-IB (+0 / 2 / 4m stretch) | S-IVB | 8x Minuteman-1
INT-16 | 2-5 UA1205/6/7 Cluster | S-IVB |  
INT-27 | 156" SRM | S-IVB | 2 -4 156" SRM
  

**1967 Saturn 1B MLV for AAP Earth Orbital Missions**

Variant | First  |  Second | Boosters |
-- | -- | -- | --
MLV-S-IB-11.5 | S-IB | S-IVB | 4x UA1205 (Stage 0)
MLV-S-IB-11.5A | S-IB (4+4 ignition) (+3.8m) | S-IVB | 4x UA1205
MLV-S-IB-11.7A | S-IB (4+4 ignition) (+3.8m) | S-IVB | 4x UA1207
MLV-S-IB-13.7 | S-IB (+3.8m) | S-IVB | 2x UA1207
MLV-S-IB-14 | S-IB (+2m) |   | 4x Minuteman-1

![S-IB INT-05A](https://user-images.githubusercontent.com/12999059/142665127-a56b0514-73af-4a73-952a-e743e5f87e92.png)

**Comment by friznit** [comment]
![The-One-After-Jupiter](https://user-images.githubusercontent.com/12999059/142856627-3a67181a-899e-44d0-a4f1-29d59b491ebd.png)

**Comment by friznit** [comment]
**ETS Apollo**

Originally designed for the Apollo Application Project, Block III is used as a ferry for Skylab 5 and early Spacelab missions.

![Apollo AAP Block III](https://user-images.githubusercontent.com/12999059/142886114-8bf03e15-f204-4e11-91d9-1998413aea59.png)

Block III+ is an advanced model for 5 astronauts and features a separate Mission Module. After launch, the CSM docks with the MM stored on top of the S-IVB stage and then proceeds to the space station.

Block IV is built to use the additional payload capacity of the Saturn M02.  It has on an extended service module (common with Aardvark Block II) and features a larger, more capable Mission Module.

![Apollo ETS Block III+   IV](https://user-images.githubusercontent.com/12999059/142886174-9ef818b1-06aa-4f26-89ff-61a15f4f61e5.png)

Block V is a a developmental crew transport vehicle for Project Constellation, aiming to carry crew to the Earth-Moon L2 Lagrange region.

![Apollo ETS Block V](https://user-images.githubusercontent.com/12999059/142886215-6ae75bd7-2a72-4501-92f9-bd58ae67297f.png)

**Comment by friznit** [comment]
![ETS_AARDV Blk 1-2](https://user-images.githubusercontent.com/12999059/150132820-e0747935-aa86-45d9-bd66-6253e5353c3a.png)

_ETS AARDV Blk 1 & 2_

**Comment by Morphisor244** [comment]
May be a bit obvious, but the S-I build is missing the S-I engine mount text indicator at the bottom.

**Comment by friznit** [comment]
The Apollo-Soyuz Test Project (ASTP) was the first crewed international space mission and the last manned US spaceflight until the launch of the Space Shuttle six years later.  The mission required a modified Apollo with extra propellant tanks and a specialised docking module compatible with both spacecraft.  Historically, Apollo was the 'active' spacecraft that manoeuvred into position to dock with Soyuz.

The Apollo command and service module is launched on a Saturn IB with the ASTP docking module stowed in the launch-vehicle adapter using a purpose-built SLA truss.  Once in orbit, the CSM extracts the docking module and manoeuvres into position to dock with Soyuz.  Soyuz 7K-TM and compatible docking ports are available in the Tantares mod and a build guide is available on the [Unofficial Tantares Wiki](https://github.com/friznit/Unofficial-Tantares-Wiki/wiki).

![ASTP](https://user-images.githubusercontent.com/12999059/153195184-504c14e6-1bc1-41f4-8201-f8e0f1a84ba3.png)

**Comment by friznit** [comment]
![Saturn I Pegasus](https://user-images.githubusercontent.com/12999059/164185450-67f34d18-fade-4420-ae80-0b896a2c2a9f.png)

**Comment by CobaltWolf** [comment]
> ![image](https://user-images.githubusercontent.com/12999059/158577131-f5732eec-f2e1-49fd-9fc4-b09184f1b5d7.png)

typos

**Comment by CobaltWolf** [comment]
> ![ETS_AARDV Blk 1-2](https://user-images.githubusercontent.com/12999059/150132820-e0747935-aa86-45d9-bd66-6253e5353c3a.png)
> 
> _ETS AARDV Blk 1 & 2_

What are those solar panels on the AARDV Block 2? They're not from BDB

**Comment by friznit** [comment]
> > > _ETS AARDV Blk 1 & 2_
> 
> What are those solar panels on the AARDV Block 2? They're not from BDB

There are no solar panels.  That's the interior of the unpressurized cargo segment.  I can see how that's misleading though so will redo the pic.
