### ISSUE TITLE
Engines

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#61]
**RL20-P3**
Pratt & Whitney's first proposal for a staged combustion cycle design. It was mentioned in at least one Saturn improvement study as a drop in replacement for J2 or the highly-conceptual HG-3 on Saturn II.

**XLR-129**
XLR-129 is a direct successor to the RL20 and has a similar powerhead where the turbos and pre-burner connect to a central chamber above the combustion chamber.  However instead of a Y shape, this uses a triaxial arrangement and adds low pressure pumps/inducers upstream of the main turbos.  It was originally meant for the ISINGLASS B52-launched rocket-powered boost glide spy plane and was later proposed for the shuttle programme, though it lost out there to Rocketdyne's RS25.  It has a unique dual mode feature which allows it to function either with its nozzle extension retracted or extended for optimal performance at sea level or altitude.

**RS-30**
Rocketdyne's RS-30 resulted from a study to select an optimum configuration for a 20 klbf hydrolox topping-cycle engine (old terminology for staged combustion).  While slightly less powerful than late model RL10 engines, it could serve as a drop in replacement and the extraordinarily high vacuum ISP makes the engine ideal for long duration on orbit applications, such as the IPP space tug.

**M-1**
Aerojet's massive M-1 was originally conceived during NASA's early Nova programme, which was setup to study a range of lunar direct ascent rocket designs.  After Saturn was selected for the lunar missions, work turned to the post-Apollo era and crewed interplanetary expeditions.  Several concepts from this second round of studies (also known as Nova, although largely unrelated to the earlier designs), used an uprated M-1 as a second stage engine as well as a first stage engine replacing the F-1.  The engine can be switched between the vacuum model and a sea level optimised version in the editor.

**E-1**
Occupying a middle ground between the H-1 and the F-1 booster engines, the E-1 is a bit of a curious use case. Originally developed for the Titan I first stage (where it would be accompanied by a pair of LR-101 verniers), it was later proposed in a 4-engine cluster for the Saturn I first stage.

**Comment by friznit** [comment]
![screenshot10](https://user-images.githubusercontent.com/12999059/118459233-76b7d780-b6f3-11eb-8191-cb0602bd612a.png)

**Comment by zorg2044** [comment]
Don't forget the Rocketdyne RS-30

https://www.alternatewars.com/BBOW/Space_Engines/Rocketdyne_Engines.htm

"Resulted from a 10-month study to select an optimum configuration for a 20 klbf Hydrolox Topping-cycle engine. Used as a test bed to estimate scaled down features/components of SSME and to also demonstrate the feasibility of a high pressure hydrolox upper stage engine."

Topping cycle being an old timey way of saying staged combustion. Apart from this snippet, the documents within indicate that it was considered for the IPP space tug, was capable of self ullage and used torch igniters for the capability to restart potentially hundreds of times.

Features 1:400 expansion ratio and over 2000psi of chamber pressure to produce 473.4s of Isp, the highest for a chemical engine in BDB. 

The baseline design had a fixed nozzle but the BDB version uses the retractable nozzle which was considered for space reduction in the shuttle payload bay.

In addition they looked at modifying the baseline design to see if the inlets and fittings could be changed to match the RL10 as a drop in replacement and was deemed to be quite possible and easy to do so.
