### ISSUE TITLE
Provide example craft files

### ISSUE THREAD

**Issue by nilswinking** [friznit/Unofficial-BDB-Wiki#62]
I think it would be great to provide example craft files because sometimes it is difficult to understand how they have to be assembled. I have build all ISS parts and some of the rockets and would create a PR for them and future vehicles.

**Comment by friznit** [comment]
Craft files are included in the BDB download.

**Comment by nilswinking** [comment]
But not for the ISS if I recall correctly, because that uses parts from different mods too.
