### ISSUE TITLE
Text in images with transparent backgrounds are invisible with Github dark mode

### ISSUE THREAD

**Issue by bigyihsuan** [friznit/Unofficial-BDB-Wiki#63]
There are various images on the wiki that have transparent backgrounds but have text that is dark like the Github dark theme.

A fix would be to have a white background on these images, like other images on the wiki.

**Pages Affected:**

* [Vanguard](../wiki/Vanguard)
* [Redstone](../wiki/Redstone)
* [Thor](../wiki/Thor)
* [Prometheus I](../wiki/Prometheus-I)
* [Prometheus II](../wiki/Prometheus-II)
* [Delta IV](../wiki/Delta-IV)
* [Saturn C](../wiki/Saturn-C)
* [Saturn V](../wiki/Saturn-V)
* [Upper Stages](../wiki/Upper-Stages)
* [Crew Modules](../wiki/Crew-Modules)
* [GATV](../wiki/GATV)
* [Ranger](../wiki/Ranger)
* [Mariner](../wiki/Mariner)
* [Nimbus](../wiki/Nimbus)
* [Keyhole](../wiki/Keyhole)
* [Communications](../wiki/Communications)
* [Science](../wiki/Science)
* [Shuttle-Derived Launchers](../wiki/Shuttle-Derived-Launchers)

There may be more pages I've missed.

**Comment by friznit** [comment]
Well that sucks. All the images with text are on transparent backgrounds.  I may or may not get around to redoing them one day but it's a lot of work and the vast majority of non-regular github users will be on the default white theme.

**Comment by Blu3wolf** [comment]
Isnt the dark theme the default for new users now?

**Comment by bigyihsuan** [comment]
Opening in incognito mode shows that the default theme is dark mode:

![image](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12767476/95f0d37b-df53-441c-aab5-de8524be603b)

It would be really nice if a white background gets added.
