### ISSUE TITLE
Vanguard page missing/incorrect table entries

### ISSUE THREAD

**Issue by b-gybels** [friznit/Unofficial-BDB-Wiki#64]
The table on the Vanguard page shows only two stages instead of three, with the 3rd stage in the 2nd stage column, also the Stage 1 column is blank, idk if this is intentional or not.

**Comment by friznit** [comment]
You're absolutely right of course - I think I probably didn't bothered to fill in the whole table since the only difference between variants (in BDB build terms at least) is the solid rocket motor.

**Comment by b-gybels** [comment]
Ah ok.

While I have an issue open, there are also a few other things I've just noticed. The Delta M uses 3x Discosuri 2 (Castor-2) SRBs in the standard (M) configuration, instead of none. Also, on the upper stage page, in the description for the HOSS, it says 0.938m instead of 0.9375, again not sure if this is deliberate or a typo.

**Comment by friznit** [comment]
Good spots, not sure how I missed that after all this time - thanks!
