### ISSUE TITLE
ISS, Rassvet and Pirs are incorrectly labeled 

### ISSUE THREAD

**Issue by of-ravens-claw** [friznit/Unofficial-BDB-Wiki#65]
Pirs and Rassvet have their names reverted.

![ISS Russian Orbital Segment](https://user-images.githubusercontent.com/44535997/141707986-c0e07840-537a-496b-863a-d85b6241f576.png)

**Comment by friznit** [comment]
Technically I don't have Rassvet on the guide at all and should have labelled the lower docking module as Pirs (the Rassvet model didn't exist in Tantares when I did it).  Anyway, Pirs has been replaced by the Nauka module now, so the guide needs a new chapter.  It'll be a while before I get back to doing ISS things though, so will have to stay as it is for the time being.

**Comment by of-ravens-claw** [comment]
I see, thanks!
