### ISSUE TITLE
Skyblab / Spacebabble / Emlemlem

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#68]
PSketch 1/2

- [x] Powah towah
- [x] STS Spacelab
- [x] EOSS
- [x] Reboost
- [x] LM Shizzle
- [ ] Shelab
- [x] Lunar Flying Vehicle
- [ ] Renovated Command Module Lab
- [ ] Little Joe
- [ ] SII Wetlab
- [x] Helios Update
- [x] Minotaur / Taurus / Minuteman
- [x] MORL
- [ ] Kepler
- [x] Surveyor
- [ ] Syncom
- [ ] TACSAT/TACOMSAT

Next Release
- [ ] Viking
- [x] Atlas Revamp
- [ ] X-15
- [ ] Seasat
- [ ] Comet HLLV
- [ ] Titan B9 switches, validate guides

Still on the To Do List:
- [ ] [ETS Pegasus Upper Stage](https://forum.kerbalspaceprogram.com/index.php?/topic/122020-112x-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v190-%D0%BF%D1%80%D0%BE%D0%B1%D0%B5-13dec2021/&do=findComment&comment=4106564)
- [ ] Tianjia Station (Dawn of the Dragon Alt History)
- [x] [Agena Horizon Scanner](https://forum.kerbalspaceprogram.com/index.php?/topic/122020-112x-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v190-%D0%BF%D1%80%D0%BE%D0%B1%D0%B5-13dec2021/page/979/#comment-4097533)
- [x] Centaur Kick Stage
- [x] Centaur Updates

**Comment by friznit** [comment]
Skylab Reactivation Project

A proposal using the Space Shuttle to reactive Skylab and extend its operational life.

- Mission 1 STS-2A (Columbia) boosts Skylab to a higher orbit using a remote-controlled Teleoperator Retrieval System, adding five years of operational life.  The TRS can also be launched on Titan III or Atlas Agena.

[TRS]

- Missions 2 & 3 attach a docking adapter, conduct repairs & replace worn system components

[Docking Adapter]

- Mission 4 attaches a 25kw solar-powered Power Expansion Package

[Power Tower]

- Over the next five years, Skylab is expanded to accommodate eight crew with a new docking module, additional logistics modules, Spacelab modules and pallets and an orbital vehicle space dock using the shuttle's external tank.

[The full monty with STS docked]

**Comment by friznit** [comment]
### Early Orbital Space Station (1967)
Pre-Skylab concept for an advanced orbital workshop based on the S-IVB stage of Saturn V.  The S-II booster stage stays attached to provide space for a crew of 9.  EOSS could be tumbled end over end to provide artificial gravity.

**Comment by zorg2044** [comment]
There seems to be at least two different takes on EOSS. May or may not be doing the full tether for the SII counterweight but we also have the other EOSS with the S4B to SII interstage space being utilised instead.

**Comment by friznit** [comment]
### Lunar Module Derivatives

**Apollo Applications Extended Lunar Surface Missions**
Apollo Applications Programme proposed a number of modified Lunar Modules for extended stay and exploration on the lunar surface.

- LM Shelter is the LM with the ascent stage engine and fuel tanks replaced by life support and science experiments.  It is landed autonomously and the orbiting Apollo CSM returns home.

[LM Shelter] (Note: descent module set to "Truck" config)

- LM Taxi is used in a subsequent mission to ferry a crew of 3 to the surface, where they transfer to the LM Shelter for the duration of their stay.

[LM Taxi]

- LM Truck is used for unmanned delivery of payloads to the surface.  It has a modified descent stage with a cargo platform replacing the ascent stage and includes an extendable ramp for deploying rovers.

[LM Truck]

**Other Applications**
- LM Lab is an ascent stage with the engine and fuel removed to provide space for science experiments and supplies to support 3 crew for up to 30 days in orbit.  It is launched on Saturn V or Saturn IB.

**Comment by friznit** [comment]
### MORL

Orbital lab proposals for either Gemini or Apollo (+derivatives) launched on Saturn IB.  Intended for lateral docking with a swing arm to pivot craft to the front. This is problematic in KSP so radial docking ports provided instead.  Equipment bay is for science experiments or supplies as desired.  Alternative to solar panels is Plutonium Brayton-cycle Generator (large but efficient RTG).  Equipment rack in base houses 3.  4x resistojet electric RCS pods can use either hydrogen or monoprop.  Original concept to use biowaste H2 by-product from ECLS water electrolysis system.

![image](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/1cf95a75-75ef-4d22-a49a-0dcb77aba088)

![image](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/a59b2962-10c7-4253-a8c4-30b9abf5e8bf)
