### ISSUE TITLE
MRV

### ISSUE THREAD

**Issue by friznit** [friznit/Unofficial-BDB-Wiki#70]
**Munar Roving Vehicle**

- The MRV wheels have individual part switches: the dust flaps should be facing rearwards
- The MRV in its transit configuration is stored in the cut out portion of the MLEM Descent Stage (use the "J-Class" config switch) attached to a hinge joint and slider for deployment on the surface
- The hinged version of the MRV requires Breaking Ground DLC.  A fixed non-foldable version is available but will require alternative transport arrangements
- Fill the MLEM Q3 Cargo Bay with additional MRV parts to balance the load during landing.  Any remaining parts can go in the Descent Stage cargo storage
- The cargo space on the MRV itself is intended for ALSEP stations and experiments.  Do not put anything in the rover storage during transit
- The additional parts are fitted to the MRV by an engineer once deployed on the surface.  Point the MRB due North before starting so you don't have to rotate parts as much
- Recommended settings for hinge parts to minimise issues:  keep motors engaged; lock only the base deployment hinge; do not lock the chassis hinges; do not use autostruts.
- Tweak the resting position of suspension in advanced tweakables so it sits roughly in the middle of the suspension travel to avoid excessive bouncing at the suspension limits (this is a Unity bug).

![LRV Build Guide](https://user-images.githubusercontent.com/12999059/178555981-c2d1f4db-be45-4ebe-b07a-3caac53ef696.png)

**Comment by Rodg88** [comment]
Each wheel has it's own mesh to switch to, Front left and right, and back left and right. Also the "J-CLass Cargo Module" which is attached opposite the MRV balances it out for flight, when it contains the HGA and TV camera, the fore and aft pallets, tool rack, grab experiment, and SEP antenna.

**Comment by Rodg88** [comment]
I'd also suggest placing the seats first, as that covers up the nodes which would otherwise make placing the aft chassis a little tricky.

**Comment by OrbitalManeuvers** [comment]
> I'd also suggest placing the seats first, as that covers up the nodes which would otherwise make placing the aft chassis a little tricky.

Another take on this ... I like the idea (I think this is what's shown) of placing the chassis parts first, then unfolding them, then placing the wheels, then the seats, then retracting wheels, then chassis parts. Expecting folks to rotate the wheels such that they'd attach correctly to the closed chassis might be less understandable and harder to illustrate.

**Comment by Rodg88** [comment]
The RO branch of KJR will cause issues, use KJR:Next instead.

**Comment by Rodg88** [comment]
If it’s overly bouncy, eg on kerbin without any of the additional parts added, use the spring power advanced tweakable of the wheels to tweak the resting position of the suspension, so it sits close to the middle of the suspension travel. If the suspension is maxed out in either direction, it can cause various issues.

**Comment by sTc2201** [comment]
Is this a concept or where are these parts? I couldn't find them in the expansion pack either.

**Comment by Lodkins** [comment]
> Is this a concept or where are these parts? I couldn't find them in the expansion pack either.

LRV I believe is on BDB GitHub in the 1.11 Dev Branch
