### ISSUE TITLE
Integrate Artemis Construction Kit

### ISSUE THREAD

**Issue by senicluxus** [friznit/Unofficial-BDB-Wiki#74]
Doing this allows the wiki to update the 'Shuttle Derived Launchers' section as well as the 'Exploration Upper Stage (EUS)' with the very high quality models included in the mod. It is essentially a more up to date reDIRECT. 

SLS Block 1, Block 1B, and Block 2 can all be added.

Orion can be updated.

This also allows adding the 'Human Landing System (HLS)' included in the mod in the lander section, and uses BDB RL-10 engines.

**Comment by AllThingSpace33** [comment]
I second this.
