### ISSUE TITLE
Vulcan page: unknown part

### ISSUE THREAD

**Issue by OrbitalManeuvers** [friznit/Unofficial-BDB-Wiki#75]
This page:
https://github.com/friznit/Unofficial-BDB-Wiki/wiki/Vulcan

references this part:
ACES/Centaur V Fuel Cell (in x2 symmetry)

Any idea where this part comes from?

**Comment by OrbitalManeuvers** [comment]
Just noticing that the tag "Vulcan" brings up the stock fuel cell - perhaps the part was dropped in favor of the stock one getting an LH2 patch?

**Comment by friznit** [comment]
If you're using restock the part doesn't get cloned/renamed because restock already has a hydrolox fuel cell:

https://forum.kerbalspaceprogram.com/index.php?/topic/196738-111x-hephaistos-stockalike-ula-vulcan-official-stand-alone-bdb-expansion/&do=findComment&comment=3855669
