### ISSUE TITLE
Atlas revamp 2024

### ISSUE THREAD

**Issue by zorg2044** [friznit/Unofficial-BDB-Wiki#78]
<img width="1395" alt="image" src="https://github.com/friznit/Unofficial-BDB-Wiki/assets/39182212/1bd89446-428b-4bf6-9798-fc938ad714f1">

<img width="1469" alt="image" src="https://github.com/friznit/Unofficial-BDB-Wiki/assets/39182212/a7ae142d-eba7-463a-bc2a-c585c08e084f">

WIP build guide for the new Atlas parts. Some bits are still pending

https://docs.google.com/spreadsheets/d/1QKUCvDAlZr2Li7REsgmhNlqYa59Yy76t1sbaCrnTXrI/edit?usp=sharing

**Comment by friznit** [comment]
## First Gen

**Atlas A-F** - Atlas D was the first operational ICBM and the starting point for subsequent space launch vehicle derivatives.  Atlas B launched SCORE that replayed the first recorded voice message from orbit.  Retired Atlas E/F later repurposed for variety of satellite launches.  Mostly used solid kick stages for orbital insertion except Atlas 23F, which used Agena D to boost Seasat into orbit.

**Atlas Able** - cobbled together by NASA adding existing Vanguard second stage to a USAF launch vehicle.  Didn't work.

**LV-3A** - Agena A upper stage was a stop gap until Agena B, which was flown by both USAF and NASA and culminated in the first successful flyby of Venus by Mariner 2.  Agena D was initial step towards a standardised launch system, designed to fly on Thor, Atlas and Titan.

**LV-3B** - Mercury was first US manned (and chimped) space flights.

**LV-3C** - Centaur was first liquid hydrogen fuelled upper stage.  Jettisoning the insulation on the way up sheds dry mass and allows for greater payload capacity.

## Second Gen

**SLV-3** - Standardised launch vehicle with Agena D upper stage.  Successfully launched Gambit-1, Lunar Orbiter, Mariner 5, GATV and SNAP-10A, the first (and only) US orbital nuclear reactor.  Also launched ATDA with no upper stage.

SLV-3A - Stretched "long tank Atlas" or "Improved Atlas for Agena", launched OGO-5 and some secret ELINT satellites.

SLV-3B - Take LV-3C first stage, add Agena D and an OAO-1 satellite all wrapped up inside a big fairing and lob into orbit at Gas Mark 5.  Only happened once.

**SLV-3C** - Standardised launch vehicle with Centaur D upper stage.  Successfully launched Surveyor, Mariner and Pioneer satellites.

SLV-3D - Similar to SLV-3C but with improved Centaur D-1A upper stage.

**Atlas G / Atlas 1** - Basically SLV-3D but with a stretched tank.  Branded as Atlas 1 for commercial launch services.

Atlas H - SLV-3D with a Multi Satellite Dispenser solid motor upper stage instead of Centaur.

## Third Gen

**Atlas 2/2A(S)** - Upgraded Atlas with stretched tanks, new engines and a roll control thruster on the new Centaur II interstage replacing the old verniers.  2AS added four Caster 4A SRBs, two ground-lit and two air-lit.

## Fourth Gen

**Atlas 3A/B** - New generation simplified "single stage Atlas" using a powerful RD-180 engine that would allow for removable of one of the two Centaur engines.  3B introduced the stretched Centaur 3 (standardised "Common Centaur")

**Comment by friznit** [comment]
## Background

Originally designed as an ICBM, the iconic Atlas rocket (BDB Bossart) launched the first four American astronauts into orbit in Project Mercury. Atlas D derived variants have a unique stage and a half design, jettisoning the booster engines to save weight and using the sustainer engine alone to finalise orbit.

As a rough guide, jettison the booster stage at 3.5 to 4G, either manually or with the auto jettison option in the booster skirt Part Action Window. Burn time should extend from around 30s to 2 minutes at just above 1G.  For a more precise estimate of when to stage the booster skirt for a given payload:

1. Build the rocket with payload in the VAB
1. Remove the booster skirt with its engines
1. Reduce fuel in first stage until TWR is just great than 1
1. Re-attach the booster skirt and make a note of the time remaining in stage burn (e.g. 30s)
1. Refuel the tanks
1. Launch and stage at the noted time remaining

Refer to Marcelo Silveira's Atlas Payload Performance graphs for details.

[![Icon_Atlas_Payload](https://user-images.githubusercontent.com/12999059/96424799-21662700-11f3-11eb-906d-1e1976d8b050.png)](Atlas-Payload-Performance)

Tags: Bossart, Belle, Inon, Hermes

## First Generation
The first generation launch vehicles were derived from the Atlas D ICBM and used LR-89-NA5 booster engines with a single LR-105-NA5 sustainer.  Initial attempts at using a liquid fuelled Able (BDB Alpha) upper stage borrowed from Vanguard were unsuccessful but development of Agena (BDB Belle) led to a true work horse launch vehicle.  LV-3C is the original Atlas Centaur (BDB Inon) featuring the first ever liquid hydrogen upper stage.

![Atlas First Gen Line Up](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/776b124c-5f7a-4b17-b723-673e5e4931f1)

## Variants
|Launch Vehicle|Boosters|Sustainer|Core Tank|Extension|Upper Stage|Remarks|
|---|---|---|---|---|---|---|
| Atlas A        | XLR-89  | None     | A |              | Nosecone     | Prototype A Red Skirt    |
| Atlas B        | XLR-89  | XLR-105 | B |              | "Chatterbox" | Prototype B Silver Skirt |
| Atlas C        | LR89-3  | LR105-3 | C |              |                       | D Silver Skirt              |
| Atlas D        | LR89-5  | LR105-5 | D |              |                      |  D Silver Skirt             | 
| Atlas Able   | LR89-5  | LR105-5 | D |              | Alpha            |  D Silver Skirt             |
| LV-3A          | LR89-5  | LR105-5 | LV3 |          | Belle A/B/D  |                                   |
| LV-3B          | LR89-5  | LR105-5 | D |              | Hermes         |                                   | 
| LV-3C          | LR89-5  | LR105-5 | D | SLV-3B  | Inon D          |                                   |

## Basic Build Guide
- Atlas Able (BDB Bossart Alpha) uses a specific 0.9375m Interstage that interfaces with the Able's SIF Interstage Adapter.
- The conical adapter tank has variant part switches to fit Mercury (BDB Hermes) crew pod or the Multi Satellite Dispenser.
- Atlas LV-3C uses the Short Centaur (BDB Inon) Interstage and the shortest BT3 extension tank (SLV-3V Config) above the core fuel tank.
- Atlas A & B use the Prototype Booster Skirt.  Almost all other builds use the standard skirt with the Default Config.  The sustainer engine attaches directly to the aft adapter tank and then the booster skirt is placed on the top node of the adapter.
- Two "Crow" radial engines go on the triangular flat spots on the side of the core tank for roll control.
- Atlas ICBMs (A-F) feature a single separation motor at the top of the long side pod.  Use a single Muo 5 sep motor for this.
- LV-3C (and all later Atlas Centaur variants) uses 8 retro motors to help with separation when staging Centaur.  These attach to the core stage just above the booster skirt in 4 pairs of 2.

![Atlas LV-3A Agena D Guide](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/66036757-9332-4348-8f95-8aaa1b54115e)

_Atlas LV-3A Agena D_

**Comment by friznit** [comment]
## Second Generation
SLV-3 is the first dedicated satellite launch vehicle with uprated LR89-7 and LR105-7 engines and a standardised Agena D upper stage.  It successfully launched Gambit-1, Lunar Orbiter, Mariner 5, the Gemini-Agena Target Vehicle and SNAP-10A, the first (and only) US orbital nuclear reactor.  SLV-3C sports the Centaur D upper stage, later upgraded to the Centaur D-1A.  Atlas G and it's similar cousin Atlas 1 flew until 1997.

Retired Atlas E/F ICBMs were repurposed for variety of satellite launches. They mostly used solid kick stages for orbital insertion except Atlas 23F, which used Agena D to boost Seasat into orbit.

![Atlas Second Gen Line Up](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/e2c1a507-c596-4266-878d-0054677244ed)

## Variants
|Launch Vehicle|Boosters|Sustainer|Core Tank|Extension|Upper Stage|Remarks|
|---|---|---|---|---|---|---|
| SLV-3          | LR89-7 | LR105-7 | LV3 |               | Belle D       |       |
| SLV-3A        | LR89-7 | LR105-7 | LV3 | SLV-3A  | Belle D       |       |
| SLV-3B        | LR89-7 | LR105-7 | LV3 | SLV-3B   | Belle D       | Belle D inside SLV-3B fairing |
| SLV-3C        | LR89-7 | LR105-7 | D    | SLV-3C   | Inon D       |      |
| SLV-3D        | LR89-7 | LR105-7 | LV3 | SLV-3C   | Inon D1-A |      |
| Atlas E/F     | LR89-6  | LR105-6 | F     |               |                   | Advanced Skirt | 
| Atlas 23F     | LR89-6  | LR105-6 | F   |  SLV-3B   | Belle-D      | Seasat Fairing | 
| Atlas G / 1   | LR89-7 | LR105-7 | LV3 | Atlas 1   | Inon D1-A  | D White Skirt |
| Atlas H        | LR89-7 | LR105-7 | LV3 | SLV-3C   | MSD           | D Silver Skirt |

## Basic Build Guide
- SLV-3 builds are very similar to LV-3 but with various length extension tanks and the uprated engines.
- All SLV builds use the default Atlas D silver booster skirt.

![Atlas SLV-3B Guide](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/27cb94e1-aeda-48ad-ac48-c1520e60d00d)

_Atlas SLV-3B_ uses a unique fairing that covers the Agena D (BDB Belle).  Start by placing the small Interstage on the Agena bottom node, then attach the Adapter Base and finally place the Fairing Base over the top.  _Atlas 23F_ is a similar setup but uses the 1.875 Fairing Base Adapter set to _23F Seasat_ config.

![Atlas SLV-3C Centaur Guide](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/76d43af1-6c2b-4ecd-b748-a6d026945ded)

_Atlas SLV-3C_ can use either Short or Long Centaur (BDB Inon) Interstage.

**Comment by friznit** [comment]
## Third Generation
Developed for the USAF MLV-3 competition in 1988, Atlas II features stretched tanks on both the first stage and Centaur upper stage and uprated RS56-OBA engines. The vernier engines are removed to make room for strap on boosters and replaced by a single roll control thruster on the Centaur interstage. The boosters are ignited in pairs, with the second set staging just after the first pair burn out.

## Variants
|Launch Vehicle|Boosters|Sustainer|Core Tank|Extension|Upper Stage|Remarks|
|---|---|---|---|---|---|---|
| Atlas 2      | SR56-OBA | SR56-OSA  | 2 | 2 | Inon 2 (2x R-10A3)  | White Booster Skirt |
| Atlas 2A    | SR56-OBA | SR56-OSA  | 2 | 2 | Inon 2 (2x R-10A4)  | White Booster Skirt |
| Atlas 2AS  | SR56-OBA | SR56-OSA  | 2 | 2 | Inon 2 (2x R-10A4)  | 4x Dioscuri-4A |

## Basic Build Guide

![front_Atlas IIaS_2](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/ff7deaae-3e34-4d6f-9566-bdd492a7c029)

_Atlas 2AS_

**Comment by friznit** [comment]
## Fourth Generation
After the merger of Martin Marietta and General Dynamics in 1993, the Atlas launch vehicle was simplified. The stage and a half design was replaced by a powerful RD-180 that allowed removal of one Centaur engine. With two engines available throughout the burn Atlas III does not need vernier engines or roll control thrusters.  3B introduced a stretched Centaur 3, standardised as "Common Centaur" for use on multiple different launch vehicles.

## Variants
|Launch Vehicle|Boosters|Sustainer|Core Tank|Extension|Upper Stage|Remarks|
|---|---|---|---|---|---|---|
| Atlas 3A  | DR-180 |   | 3 | 3 | Inon 2 (1x R-10A4)  |   |
| Atlas 3B  | DR-180 |   | 3 | 3 | Inon 3 (1x / 2x R-10A4 |   |

## Basic Build Guide
- Atlas III (BDB Bossart 3) uses 12 retro motors placed in pairs just about the joint between the core stage and the engine.

![Atlas IIIA Guide](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/5bc256a3-0c1f-4068-a25d-8a42f03d79c9)

_Atlas IIIA_ with Dual Engine Centaur II upper stage

**Comment by zorg2044** [comment]
Updated the build guide spreadsheet for the 2.5m parts.

SLV3-X is pretty straight forward. Only point to note is to use the Atlas II roll thruster. Ofc thats not period correct but all signs point to something roughly similar being used as there is no vernier.

![image](https://github.com/friznit/Unofficial-BDB-Wiki/assets/39182212/e3078361-3d36-449f-b1ff-d4a9878e2166)

![image](https://github.com/friznit/Unofficial-BDB-Wiki/assets/39182212/1acf1239-3463-49ce-9a4b-60f1bcd19b87)


The 5 engine Atlas is based on very early concepts before the design coalesced into what we know today. The design was volatile at that time and changed a lot. Even the fuel choice varied. The overall dimensions follow Ed Kyle's card. The XLR engine have the right Isp more or less although the thrust is lower than what Ed Kyle noted on Spacelaunchreport. Still it works in KSP. The XB-65 designation was in use for the missile at the time.

Users are probably best served by not focussing too much on this specific build but coming up with how the design might have evolved later. The original design used a much larger warhead too which is not represented here since most of that is part of the conical tank in our model and topped off with the smaller Atlas A instrumentation nosecone to complete the shape.

![image](https://github.com/friznit/Unofficial-BDB-Wiki/assets/39182212/01066ffe-2fd2-4227-a155-3303fbfdf564)

![image](https://github.com/friznit/Unofficial-BDB-Wiki/assets/39182212/ff2fed2f-d9c2-4820-a906-98bd5d5239d5)

![image](https://github.com/friznit/Unofficial-BDB-Wiki/assets/39182212/f244a3b7-ae51-4ae6-907f-cb542942a072)

![image](https://github.com/friznit/Unofficial-BDB-Wiki/assets/39182212/6c6446e6-2168-499d-85be-cfa5443e2990)

**Comment by zorg2044** [comment]
Updated build guide doc with CELV. More or less the same as before really, the tank lengths are the same as before but the extension tanks have been consolidated into B9PS switches.

The castor motor from the proposal is notional but the AJ60 is a good match to  the propellant load as described by Ed Kyle. Details of roll control solution is unknown but the Atlas II thruster could be placed on the fairing base (maybe even 2x).

**Comment by zorg2044** [comment]
Expanded the Atlas II and III sections and clarified the upper stage options.

**Comment by zorg2044** [comment]
aaah I just realised you had already taken some of your screenshots before we had that discussion about the LV3 tank. With the latest corrections to the sheet I believe all the Atlas Centaur variants up to Atlas I should be using the Atlas D core tank rather than LV3. All the images show the shorter of the left side avionics pod on Atlas centaur vehicles. Sorry :P

**Comment by friznit** [comment]
# Atlas Unflown

## Background
Over the course of its long life, there have been many [proposed Atlas designs](https://web.archive.org/web/20220406013828/http://www.spacelaunchreport.com/atlasnot.html) that were never developed.  Some are essentially early concepts for launch vehicles that flew many years later. Designs changed a lot over time so a degree of artistic license is encouraged when building these rockets.

Tags: Bossart, SLV3X, CELV

## Variants

|Launch Vehicle|Boosters|Sustainer|Core Tank|Extension|Upper Stage|Remarks|
|---|---|---|---|---|---|---|
| Atlas Vega               | LR89-5       | LR105-5       | D | SLV-3B        | Vejur      | _Optional_ JPL6K Third Stage |
| Atlas Vega Mercury | LR89-5       | LR105-5       | D | SLV-3B       | Vejur       | Hermes Lab & Crew Capsule |
| Atlas II-B                  | SR56-OBA | None            | 2 | 2 + SLV-3B | Inon 2     | D White Skirt                         |
| Atlas SLV-3X            | LR89-7       | H-1D (1973) | SLV-3X (No Vernier) | SLV-3X | Inon D | D Silver Skirt      |
| Atlas XB-65             | XLR-89 x4   | XLR-105        | SLV-3X (Vernier) | SLV-3X + Short | Atlas A Nosecone | 2.5m Booster Skirt  |
| Atlas SLV-3K            | H-1D x4       | H-1D (1973) | SLV-3X (No Vernier) | SLV-3X | Inon D | D Silver Skirt      |
| Atlas CELV              | H-1D x4       | H-1D            | SLV-3X | SLV-3X | Inon G'/T | Prometheus 3.125m Fairing   |

## Basic Build Guide
Atlas-Vega is a variant of Atlas LV3-C with a Vega (BDB Vejur) second stage powered by a Vanguard (BDB Viklun) first stage engine. In the three stage variant, a JPL 6K stage taken from Juno IV (BDB Chryslus) can be added.  Vega is a drop in replacement for Centaur and uses the same interstage and fairing base under the avionics unit.

![Atlas Vega](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/c39f97d6-14ed-4341-9bc5-f8b054fc1ae9)

The SLV-3X designation is reused often to refer to experimental designs.  The 1970 SLV-3X is a "fat" Atlas SLV-3C with expanded 2.5m diameter (KSP Scale) first stage tanks and an H-1D sustainer engine in place of the LR105-7.  A roll control system on the interstage is used in place of verniers.

![Atlas SLV-3X](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/446164c7-d348-489b-a7dd-087b9c1930da)

XB-65 is an early five engine concept boosted by 4x XLR-89 engines and a single XLR-105 sustainer.

![Atlas XB-65](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/5bb6da56-18e6-40a6-b633-f48bf7f6e222)

SLV-3K is an even fatter Atlas with 3.125m diameter tanks boosted by 4x H-1D engines and a single H-1D sustainer topped by a Centaur D-1 and a widened fairing.

![Atlas SLV-3K](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/faea8b9c-5c2d-4f57-9563-4e374bb2ec68)

Atlas II Centaur G Prime (not to be confused with the later Atlas II that actually flew) was proposed for the USAF Complementary Expendable Launch Vehicle (CELV) competition in 1984.  It features a 3.125m diameter first stage powered by 5x H-1D engines and 4x SRB's not dissimilar to the AJ-60A's used on Atlas V.

![Atlas CELV](https://github.com/friznit/Unofficial-BDB-Wiki/assets/12999059/dceee625-ec21-4257-908e-9b5424618ba8)

**Comment by zorg2044** [comment]
@friznit the XB-65 is all XLR89 and XLR105 not H1Ds (table is correct, the write up is wrong)

**Comment by zorg2044** [comment]
Also probably worth including Atlas K in the fictional list. Build should be same as the old one.

**Comment by zorg2044** [comment]
Updated with OV-1 Atlas D builds

1) Atlas D with Single Atlas Retained Structure (ARS) side mount pod, 45 deg to right on side without lox pipe. ABRES nose cone is not planned so it can be substituted with the Atlas A nosecone instead.
2) Dual ARS nose mounted pod + Scientific Passenger Pod (planned but not done yet)
3) Dual ARS nose mounted pod + ARS side mount pod

Atlas F OV-1 fairing and decouplers are still pending.

https://space.skyrocket.de/doc_lau_det/atlas-d_ov1.htm
https://space.skyrocket.de/doc_lau_det/atlas-ef_ov1.htm

**Comment by zorg2044** [comment]
There was a mistake in the build spreadsheet and indeed the models, the Atlas H adapter part is not a tank but structural. This is being removed from the model and the structural part will be made together with the fairing soon.

![image-1](https://github.com/user-attachments/assets/42ebe33f-f3b5-403c-bcf7-ddaae143edcd)

![atlas_h_msd_3](https://github.com/user-attachments/assets/001b366a-b076-46e5-a2ec-eb55af196833)

![image](https://github.com/user-attachments/assets/5547b3c9-e7cc-4c99-8441-6ff8f5a919b6)

**Comment by zorg2044** [comment]
I think the build guide spreadsheet is now complete. Everything needed for the historical builds is now in game except for a properly sized Burner II kit and fairing. That will be in a future update. The Scientific Passenger Pod is also pending but thats not really part of a specific build. Just a mission specific addon. 

Non historical section has been fleshed out as well.
