### ISSUE TITLE
Kerbal Concepts: Athena IIcS redirects to Indian slot machine site

### ISSUE THREAD

**Issue by BSSSNAG** [friznit/Unofficial-BDB-Wiki#79]
https://www.spacelaunchreport.com/athenachart.jpg now redirects to https://www.kajahl.com/ . Instead of  the appropriate image. What is shown below:
![Screenshot 2024-06-18 202510](https://github.com/friznit/Unofficial-BDB-Wiki/assets/83569489/9864ca77-5a0e-4973-9cde-b7677efae418)

**Comment by friznit** [comment]
Ah.  Space Launch Report died years ago.  I'll remove the link.  Thanks!

**Comment by zorg2044** [comment]
Could update any SLR links to point to archive.org's saved version of it.

**Comment by BSSSNAG** [comment]
This one could be a drop in replacement possibly.
https://web.archive.org/web/20220314185454/spacelaunchreport.com/athenachart.jpg
