### ISSUE TITLE
B9PartSwitch Fatal Error with X-15

### ISSUE THREAD

**Issue by marxman28** [friznit/Unofficial-BDB-Wiki#84]
![image](https://github.com/user-attachments/assets/5a408c04-0059-4aa8-a0d8-b8dc87f6109b)

I just dropped the X15 folder in to my BDB folder. Is there another folder that I also have to install?

**Comment by BSSSNAG** [comment]
try asking this on the relevant forum page here https://forum.kerbalspaceprogram.com/topic/122020-1125-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v1140-%D0%BC%D0%B5%D1%82%D0%B0%D0%BB%D0%BB-30sep2024/. Try doing a clean install of BDB 1.14

**Comment by marxman28** [comment]
> try asking this on the relevant forum page here https://forum.kerbalspaceprogram.com/topic/122020-1125-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v1140-%D0%BC%D0%B5%D1%82%D0%B0%D0%BB%D0%BB-30sep2024/. Try doing a clean install of BDB 1.14

I figured it out yesterday. No more error messages.
