### ISSUE TITLE
Part Switching Information

### ISSUE THREAD

**Issue by TheGLine** [friznit/Unofficial-BDB-Wiki#9]
Adding a brief reminder about those parts in rockets that need part switches to actually show properly would be helpful.  This would be especially helpful in the Atlas V section, since both the interstage truss and the RD-180 analogues are part switched to show the correct model.

**Comment by friznit** [comment]
Added part switch hints to Atlas V (inon interstage) and Titan (engine fairings).  Are there any others?

**Comment by TheGLine** [comment]
I don't believe so, or at least I haven't found any that weren't clear to me.

**Comment by zorg2044** [comment]
I didn't realise for the longest time the Atlas tapered tank had a part switch from 1.5m to 0.9375m :P

**Comment by friznit** [comment]
> I didn't realise for the longest time the Atlas tapered tank had a part switch from 1.5m to 0.9375m :P

It's not especially obvious given there's also an Atlas adapter part that achieves the same purpose, and practical application is limited.  I need to update the Atlas pages to bring them up to standard anyway so will add this to the guide.
